/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
)

// checks if the CreateVersionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVersionRequest{}

// CreateVersionRequest Request to create a version snapshot
type CreateVersionRequest struct {
	Tag NullableString `json:"tag,omitempty" validate:"regexp=^[a-z0-9][a-z0-9_-]{0,48}[a-z0-9]$"`
	Description NullableString `json:"description,omitempty"`
}

// NewCreateVersionRequest instantiates a new CreateVersionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVersionRequest() *CreateVersionRequest {
	this := CreateVersionRequest{}
	return &this
}

// NewCreateVersionRequestWithDefaults instantiates a new CreateVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVersionRequestWithDefaults() *CreateVersionRequest {
	this := CreateVersionRequest{}
	return &this
}

// GetTag returns the Tag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateVersionRequest) GetTag() string {
	if o == nil || IsNil(o.Tag.Get()) {
		var ret string
		return ret
	}
	return *o.Tag.Get()
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateVersionRequest) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tag.Get(), o.Tag.IsSet()
}

// HasTag returns a boolean if a field has been set.
func (o *CreateVersionRequest) HasTag() bool {
	if o != nil && o.Tag.IsSet() {
		return true
	}

	return false
}

// SetTag gets a reference to the given NullableString and assigns it to the Tag field.
func (o *CreateVersionRequest) SetTag(v string) {
	o.Tag.Set(&v)
}
// SetTagNil sets the value for Tag to be an explicit nil
func (o *CreateVersionRequest) SetTagNil() {
	o.Tag.Set(nil)
}

// UnsetTag ensures that no value is present for Tag, not even an explicit nil
func (o *CreateVersionRequest) UnsetTag() {
	o.Tag.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateVersionRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateVersionRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateVersionRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateVersionRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateVersionRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateVersionRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o CreateVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVersionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Tag.IsSet() {
		toSerialize["tag"] = o.Tag.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

type NullableCreateVersionRequest struct {
	value *CreateVersionRequest
	isSet bool
}

func (v NullableCreateVersionRequest) Get() *CreateVersionRequest {
	return v.value
}

func (v *NullableCreateVersionRequest) Set(val *CreateVersionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVersionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVersionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVersionRequest(val *CreateVersionRequest) *NullableCreateVersionRequest {
	return &NullableCreateVersionRequest{value: val, isSet: true}
}

func (v NullableCreateVersionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVersionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


