/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.1.1.dev2+gfe6303fdd.d20260209
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the S3ConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3ConfigRequest{}

// S3ConfigRequest Request model for S3 configuration
type S3ConfigRequest struct {
	// S3-compatible endpoint URL. Must start with https://
	EndpointUrl string `json:"endpoint_url" validate:"regexp=^https:\\/\\/"`
	// Access key ID for S3 authentication
	AccessKeyId string `json:"access_key_id"`
	SecretAccessKey NullableString `json:"secret_access_key,omitempty"`
	// S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores)
	BucketName string `json:"bucket_name" validate:"regexp=^[a-z0-9][a-z0-9.\\\\-]*[a-z0-9]$"`
	// Default path prefix for uploaded files. Can include slashes for folder structure
	DefaultPrefix *string `json:"default_prefix,omitempty" validate:"regexp=^[a-zA-Z0-9_\\\\-\\\\.\\/]*$"`
}

type _S3ConfigRequest S3ConfigRequest

// NewS3ConfigRequest instantiates a new S3ConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3ConfigRequest(endpointUrl string, accessKeyId string, bucketName string) *S3ConfigRequest {
	this := S3ConfigRequest{}
	this.EndpointUrl = endpointUrl
	this.AccessKeyId = accessKeyId
	this.BucketName = bucketName
	var defaultPrefix string = ""
	this.DefaultPrefix = &defaultPrefix
	return &this
}

// NewS3ConfigRequestWithDefaults instantiates a new S3ConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3ConfigRequestWithDefaults() *S3ConfigRequest {
	this := S3ConfigRequest{}
	var defaultPrefix string = ""
	this.DefaultPrefix = &defaultPrefix
	return &this
}

// GetEndpointUrl returns the EndpointUrl field value
func (o *S3ConfigRequest) GetEndpointUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointUrl
}

// GetEndpointUrlOk returns a tuple with the EndpointUrl field value
// and a boolean to check if the value has been set.
func (o *S3ConfigRequest) GetEndpointUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointUrl, true
}

// SetEndpointUrl sets field value
func (o *S3ConfigRequest) SetEndpointUrl(v string) {
	o.EndpointUrl = v
}

// GetAccessKeyId returns the AccessKeyId field value
func (o *S3ConfigRequest) GetAccessKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value
// and a boolean to check if the value has been set.
func (o *S3ConfigRequest) GetAccessKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKeyId, true
}

// SetAccessKeyId sets field value
func (o *S3ConfigRequest) SetAccessKeyId(v string) {
	o.AccessKeyId = v
}

// GetSecretAccessKey returns the SecretAccessKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *S3ConfigRequest) GetSecretAccessKey() string {
	if o == nil || IsNil(o.SecretAccessKey.Get()) {
		var ret string
		return ret
	}
	return *o.SecretAccessKey.Get()
}

// GetSecretAccessKeyOk returns a tuple with the SecretAccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *S3ConfigRequest) GetSecretAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecretAccessKey.Get(), o.SecretAccessKey.IsSet()
}

// HasSecretAccessKey returns a boolean if a field has been set.
func (o *S3ConfigRequest) HasSecretAccessKey() bool {
	if o != nil && o.SecretAccessKey.IsSet() {
		return true
	}

	return false
}

// SetSecretAccessKey gets a reference to the given NullableString and assigns it to the SecretAccessKey field.
func (o *S3ConfigRequest) SetSecretAccessKey(v string) {
	o.SecretAccessKey.Set(&v)
}
// SetSecretAccessKeyNil sets the value for SecretAccessKey to be an explicit nil
func (o *S3ConfigRequest) SetSecretAccessKeyNil() {
	o.SecretAccessKey.Set(nil)
}

// UnsetSecretAccessKey ensures that no value is present for SecretAccessKey, not even an explicit nil
func (o *S3ConfigRequest) UnsetSecretAccessKey() {
	o.SecretAccessKey.Unset()
}

// GetBucketName returns the BucketName field value
func (o *S3ConfigRequest) GetBucketName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BucketName
}

// GetBucketNameOk returns a tuple with the BucketName field value
// and a boolean to check if the value has been set.
func (o *S3ConfigRequest) GetBucketNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BucketName, true
}

// SetBucketName sets field value
func (o *S3ConfigRequest) SetBucketName(v string) {
	o.BucketName = v
}

// GetDefaultPrefix returns the DefaultPrefix field value if set, zero value otherwise.
func (o *S3ConfigRequest) GetDefaultPrefix() string {
	if o == nil || IsNil(o.DefaultPrefix) {
		var ret string
		return ret
	}
	return *o.DefaultPrefix
}

// GetDefaultPrefixOk returns a tuple with the DefaultPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ConfigRequest) GetDefaultPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultPrefix) {
		return nil, false
	}
	return o.DefaultPrefix, true
}

// HasDefaultPrefix returns a boolean if a field has been set.
func (o *S3ConfigRequest) HasDefaultPrefix() bool {
	if o != nil && !IsNil(o.DefaultPrefix) {
		return true
	}

	return false
}

// SetDefaultPrefix gets a reference to the given string and assigns it to the DefaultPrefix field.
func (o *S3ConfigRequest) SetDefaultPrefix(v string) {
	o.DefaultPrefix = &v
}

func (o S3ConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3ConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint_url"] = o.EndpointUrl
	toSerialize["access_key_id"] = o.AccessKeyId
	if o.SecretAccessKey.IsSet() {
		toSerialize["secret_access_key"] = o.SecretAccessKey.Get()
	}
	toSerialize["bucket_name"] = o.BucketName
	if !IsNil(o.DefaultPrefix) {
		toSerialize["default_prefix"] = o.DefaultPrefix
	}
	return toSerialize, nil
}

func (o *S3ConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint_url",
		"access_key_id",
		"bucket_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3ConfigRequest := _S3ConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3ConfigRequest)

	if err != nil {
		return err
	}

	*o = S3ConfigRequest(varS3ConfigRequest)

	return err
}

type NullableS3ConfigRequest struct {
	value *S3ConfigRequest
	isSet bool
}

func (v NullableS3ConfigRequest) Get() *S3ConfigRequest {
	return v.value
}

func (v *NullableS3ConfigRequest) Set(val *S3ConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableS3ConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableS3ConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3ConfigRequest(val *S3ConfigRequest) *NullableS3ConfigRequest {
	return &NullableS3ConfigRequest{value: val, isSet: true}
}

func (v NullableS3ConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3ConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


