/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the S3ConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3ConfigResponse{}

// S3ConfigResponse Response for S3 configuration (with masked secret)
type S3ConfigResponse struct {
	// Whether S3 is configured
	Configured bool `json:"configured"`
	// S3-compatible endpoint URL
	EndpointUrl string `json:"endpoint_url"`
	// Access key ID
	AccessKeyId string `json:"access_key_id"`
	// Masked secret access key (shows first 4 and last 4 characters)
	SecretAccessKeyMasked string `json:"secret_access_key_masked"`
	// S3 bucket name
	BucketName string `json:"bucket_name"`
	// Default path prefix for uploads
	DefaultPrefix string `json:"default_prefix"`
}

type _S3ConfigResponse S3ConfigResponse

// NewS3ConfigResponse instantiates a new S3ConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3ConfigResponse(configured bool, endpointUrl string, accessKeyId string, secretAccessKeyMasked string, bucketName string, defaultPrefix string) *S3ConfigResponse {
	this := S3ConfigResponse{}
	this.Configured = configured
	this.EndpointUrl = endpointUrl
	this.AccessKeyId = accessKeyId
	this.SecretAccessKeyMasked = secretAccessKeyMasked
	this.BucketName = bucketName
	this.DefaultPrefix = defaultPrefix
	return &this
}

// NewS3ConfigResponseWithDefaults instantiates a new S3ConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3ConfigResponseWithDefaults() *S3ConfigResponse {
	this := S3ConfigResponse{}
	return &this
}

// GetConfigured returns the Configured field value
func (o *S3ConfigResponse) GetConfigured() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Configured
}

// GetConfiguredOk returns a tuple with the Configured field value
// and a boolean to check if the value has been set.
func (o *S3ConfigResponse) GetConfiguredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configured, true
}

// SetConfigured sets field value
func (o *S3ConfigResponse) SetConfigured(v bool) {
	o.Configured = v
}

// GetEndpointUrl returns the EndpointUrl field value
func (o *S3ConfigResponse) GetEndpointUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointUrl
}

// GetEndpointUrlOk returns a tuple with the EndpointUrl field value
// and a boolean to check if the value has been set.
func (o *S3ConfigResponse) GetEndpointUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointUrl, true
}

// SetEndpointUrl sets field value
func (o *S3ConfigResponse) SetEndpointUrl(v string) {
	o.EndpointUrl = v
}

// GetAccessKeyId returns the AccessKeyId field value
func (o *S3ConfigResponse) GetAccessKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value
// and a boolean to check if the value has been set.
func (o *S3ConfigResponse) GetAccessKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKeyId, true
}

// SetAccessKeyId sets field value
func (o *S3ConfigResponse) SetAccessKeyId(v string) {
	o.AccessKeyId = v
}

// GetSecretAccessKeyMasked returns the SecretAccessKeyMasked field value
func (o *S3ConfigResponse) GetSecretAccessKeyMasked() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretAccessKeyMasked
}

// GetSecretAccessKeyMaskedOk returns a tuple with the SecretAccessKeyMasked field value
// and a boolean to check if the value has been set.
func (o *S3ConfigResponse) GetSecretAccessKeyMaskedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretAccessKeyMasked, true
}

// SetSecretAccessKeyMasked sets field value
func (o *S3ConfigResponse) SetSecretAccessKeyMasked(v string) {
	o.SecretAccessKeyMasked = v
}

// GetBucketName returns the BucketName field value
func (o *S3ConfigResponse) GetBucketName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BucketName
}

// GetBucketNameOk returns a tuple with the BucketName field value
// and a boolean to check if the value has been set.
func (o *S3ConfigResponse) GetBucketNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BucketName, true
}

// SetBucketName sets field value
func (o *S3ConfigResponse) SetBucketName(v string) {
	o.BucketName = v
}

// GetDefaultPrefix returns the DefaultPrefix field value
func (o *S3ConfigResponse) GetDefaultPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultPrefix
}

// GetDefaultPrefixOk returns a tuple with the DefaultPrefix field value
// and a boolean to check if the value has been set.
func (o *S3ConfigResponse) GetDefaultPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultPrefix, true
}

// SetDefaultPrefix sets field value
func (o *S3ConfigResponse) SetDefaultPrefix(v string) {
	o.DefaultPrefix = v
}

func (o S3ConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3ConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["configured"] = o.Configured
	toSerialize["endpoint_url"] = o.EndpointUrl
	toSerialize["access_key_id"] = o.AccessKeyId
	toSerialize["secret_access_key_masked"] = o.SecretAccessKeyMasked
	toSerialize["bucket_name"] = o.BucketName
	toSerialize["default_prefix"] = o.DefaultPrefix
	return toSerialize, nil
}

func (o *S3ConfigResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"configured",
		"endpoint_url",
		"access_key_id",
		"secret_access_key_masked",
		"bucket_name",
		"default_prefix",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3ConfigResponse := _S3ConfigResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3ConfigResponse)

	if err != nil {
		return err
	}

	*o = S3ConfigResponse(varS3ConfigResponse)

	return err
}

type NullableS3ConfigResponse struct {
	value *S3ConfigResponse
	isSet bool
}

func (v NullableS3ConfigResponse) Get() *S3ConfigResponse {
	return v.value
}

func (v *NullableS3ConfigResponse) Set(val *S3ConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableS3ConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableS3ConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3ConfigResponse(val *S3ConfigResponse) *NullableS3ConfigResponse {
	return &NullableS3ConfigResponse{value: val, isSet: true}
}

func (v NullableS3ConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3ConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


