/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)

// AppRoutersV1PdfAsyncJobStatus PDF job status values
type AppRoutersV1PdfAsyncJobStatus string

// List of app__routers__v1__pdf_async__JobStatus
const (
	PENDING AppRoutersV1PdfAsyncJobStatus = "pending"
	PROCESSING AppRoutersV1PdfAsyncJobStatus = "processing"
	COMPLETED AppRoutersV1PdfAsyncJobStatus = "completed"
	FAILED AppRoutersV1PdfAsyncJobStatus = "failed"
)

// All allowed values of AppRoutersV1PdfAsyncJobStatus enum
var AllowedAppRoutersV1PdfAsyncJobStatusEnumValues = []AppRoutersV1PdfAsyncJobStatus{
	"pending",
	"processing",
	"completed",
	"failed",
}

func (v *AppRoutersV1PdfAsyncJobStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppRoutersV1PdfAsyncJobStatus(value)
	for _, existing := range AllowedAppRoutersV1PdfAsyncJobStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppRoutersV1PdfAsyncJobStatus", value)
}

// NewAppRoutersV1PdfAsyncJobStatusFromValue returns a pointer to a valid AppRoutersV1PdfAsyncJobStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppRoutersV1PdfAsyncJobStatusFromValue(v string) (*AppRoutersV1PdfAsyncJobStatus, error) {
	ev := AppRoutersV1PdfAsyncJobStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppRoutersV1PdfAsyncJobStatus: valid values are %v", v, AllowedAppRoutersV1PdfAsyncJobStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppRoutersV1PdfAsyncJobStatus) IsValid() bool {
	for _, existing := range AllowedAppRoutersV1PdfAsyncJobStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to app__routers__v1__pdf_async__JobStatus value
func (v AppRoutersV1PdfAsyncJobStatus) Ptr() *AppRoutersV1PdfAsyncJobStatus {
	return &v
}

type NullableAppRoutersV1PdfAsyncJobStatus struct {
	value *AppRoutersV1PdfAsyncJobStatus
	isSet bool
}

func (v NullableAppRoutersV1PdfAsyncJobStatus) Get() *AppRoutersV1PdfAsyncJobStatus {
	return v.value
}

func (v *NullableAppRoutersV1PdfAsyncJobStatus) Set(val *AppRoutersV1PdfAsyncJobStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRoutersV1PdfAsyncJobStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRoutersV1PdfAsyncJobStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRoutersV1PdfAsyncJobStatus(val *AppRoutersV1PdfAsyncJobStatus) *NullableAppRoutersV1PdfAsyncJobStatus {
	return &NullableAppRoutersV1PdfAsyncJobStatus{value: val, isSet: true}
}

func (v NullableAppRoutersV1PdfAsyncJobStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRoutersV1PdfAsyncJobStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

