/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)

// AppRoutersV1AgentJobStatus the model 'AppRoutersV1AgentJobStatus'
type AppRoutersV1AgentJobStatus string

// List of app__routers__v1__agent__JobStatus
const (
	PENDING AppRoutersV1AgentJobStatus = "pending"
	PROCESSING AppRoutersV1AgentJobStatus = "processing"
	COMPLETED AppRoutersV1AgentJobStatus = "completed"
	FAILED AppRoutersV1AgentJobStatus = "failed"
)

// All allowed values of AppRoutersV1AgentJobStatus enum
var AllowedAppRoutersV1AgentJobStatusEnumValues = []AppRoutersV1AgentJobStatus{
	"pending",
	"processing",
	"completed",
	"failed",
}

func (v *AppRoutersV1AgentJobStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppRoutersV1AgentJobStatus(value)
	for _, existing := range AllowedAppRoutersV1AgentJobStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppRoutersV1AgentJobStatus", value)
}

// NewAppRoutersV1AgentJobStatusFromValue returns a pointer to a valid AppRoutersV1AgentJobStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppRoutersV1AgentJobStatusFromValue(v string) (*AppRoutersV1AgentJobStatus, error) {
	ev := AppRoutersV1AgentJobStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppRoutersV1AgentJobStatus: valid values are %v", v, AllowedAppRoutersV1AgentJobStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppRoutersV1AgentJobStatus) IsValid() bool {
	for _, existing := range AllowedAppRoutersV1AgentJobStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to app__routers__v1__agent__JobStatus value
func (v AppRoutersV1AgentJobStatus) Ptr() *AppRoutersV1AgentJobStatus {
	return &v
}

type NullableAppRoutersV1AgentJobStatus struct {
	value *AppRoutersV1AgentJobStatus
	isSet bool
}

func (v NullableAppRoutersV1AgentJobStatus) Get() *AppRoutersV1AgentJobStatus {
	return v.value
}

func (v *NullableAppRoutersV1AgentJobStatus) Set(val *AppRoutersV1AgentJobStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRoutersV1AgentJobStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRoutersV1AgentJobStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRoutersV1AgentJobStatus(val *AppRoutersV1AgentJobStatus) *NullableAppRoutersV1AgentJobStatus {
	return &NullableAppRoutersV1AgentJobStatus{value: val, isSet: true}
}

func (v NullableAppRoutersV1AgentJobStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRoutersV1AgentJobStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

