/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MergePdfRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MergePdfRequest{}

// MergePdfRequest struct for MergePdfRequest
type MergePdfRequest struct {
	// `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
	ExportType *AppRoutersV1PdfToolsExportType `json:"export_type,omitempty"`
	// URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
	Expiration *int32 `json:"expiration,omitempty"`
	Filename NullableString `json:"filename,omitempty" validate:"regexp=^[a-zA-Z0-9_\\\\-\\\\.]+$"`
	// Ordered list of PDFs to merge. Each entry has either `pdf_url` or `pdf_base64`. Minimum 2.
	Pdfs []PdfInput `json:"pdfs"`
}

type _MergePdfRequest MergePdfRequest

// NewMergePdfRequest instantiates a new MergePdfRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMergePdfRequest(pdfs []PdfInput) *MergePdfRequest {
	this := MergePdfRequest{}
	var exportType AppRoutersV1PdfToolsExportType = URL
	this.ExportType = &exportType
	var expiration int32 = 86400
	this.Expiration = &expiration
	this.Pdfs = pdfs
	return &this
}

// NewMergePdfRequestWithDefaults instantiates a new MergePdfRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMergePdfRequestWithDefaults() *MergePdfRequest {
	this := MergePdfRequest{}
	var exportType AppRoutersV1PdfToolsExportType = URL
	this.ExportType = &exportType
	var expiration int32 = 86400
	this.Expiration = &expiration
	return &this
}

// GetExportType returns the ExportType field value if set, zero value otherwise.
func (o *MergePdfRequest) GetExportType() AppRoutersV1PdfToolsExportType {
	if o == nil || IsNil(o.ExportType) {
		var ret AppRoutersV1PdfToolsExportType
		return ret
	}
	return *o.ExportType
}

// GetExportTypeOk returns a tuple with the ExportType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePdfRequest) GetExportTypeOk() (*AppRoutersV1PdfToolsExportType, bool) {
	if o == nil || IsNil(o.ExportType) {
		return nil, false
	}
	return o.ExportType, true
}

// HasExportType returns a boolean if a field has been set.
func (o *MergePdfRequest) HasExportType() bool {
	if o != nil && !IsNil(o.ExportType) {
		return true
	}

	return false
}

// SetExportType gets a reference to the given AppRoutersV1PdfToolsExportType and assigns it to the ExportType field.
func (o *MergePdfRequest) SetExportType(v AppRoutersV1PdfToolsExportType) {
	o.ExportType = &v
}

// GetExpiration returns the Expiration field value if set, zero value otherwise.
func (o *MergePdfRequest) GetExpiration() int32 {
	if o == nil || IsNil(o.Expiration) {
		var ret int32
		return ret
	}
	return *o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergePdfRequest) GetExpirationOk() (*int32, bool) {
	if o == nil || IsNil(o.Expiration) {
		return nil, false
	}
	return o.Expiration, true
}

// HasExpiration returns a boolean if a field has been set.
func (o *MergePdfRequest) HasExpiration() bool {
	if o != nil && !IsNil(o.Expiration) {
		return true
	}

	return false
}

// SetExpiration gets a reference to the given int32 and assigns it to the Expiration field.
func (o *MergePdfRequest) SetExpiration(v int32) {
	o.Expiration = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MergePdfRequest) GetFilename() string {
	if o == nil || IsNil(o.Filename.Get()) {
		var ret string
		return ret
	}
	return *o.Filename.Get()
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MergePdfRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filename.Get(), o.Filename.IsSet()
}

// HasFilename returns a boolean if a field has been set.
func (o *MergePdfRequest) HasFilename() bool {
	if o != nil && o.Filename.IsSet() {
		return true
	}

	return false
}

// SetFilename gets a reference to the given NullableString and assigns it to the Filename field.
func (o *MergePdfRequest) SetFilename(v string) {
	o.Filename.Set(&v)
}
// SetFilenameNil sets the value for Filename to be an explicit nil
func (o *MergePdfRequest) SetFilenameNil() {
	o.Filename.Set(nil)
}

// UnsetFilename ensures that no value is present for Filename, not even an explicit nil
func (o *MergePdfRequest) UnsetFilename() {
	o.Filename.Unset()
}

// GetPdfs returns the Pdfs field value
func (o *MergePdfRequest) GetPdfs() []PdfInput {
	if o == nil {
		var ret []PdfInput
		return ret
	}

	return o.Pdfs
}

// GetPdfsOk returns a tuple with the Pdfs field value
// and a boolean to check if the value has been set.
func (o *MergePdfRequest) GetPdfsOk() ([]PdfInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pdfs, true
}

// SetPdfs sets field value
func (o *MergePdfRequest) SetPdfs(v []PdfInput) {
	o.Pdfs = v
}

func (o MergePdfRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MergePdfRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExportType) {
		toSerialize["export_type"] = o.ExportType
	}
	if !IsNil(o.Expiration) {
		toSerialize["expiration"] = o.Expiration
	}
	if o.Filename.IsSet() {
		toSerialize["filename"] = o.Filename.Get()
	}
	toSerialize["pdfs"] = o.Pdfs
	return toSerialize, nil
}

func (o *MergePdfRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pdfs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMergePdfRequest := _MergePdfRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMergePdfRequest)

	if err != nil {
		return err
	}

	*o = MergePdfRequest(varMergePdfRequest)

	return err
}

type NullableMergePdfRequest struct {
	value *MergePdfRequest
	isSet bool
}

func (v NullableMergePdfRequest) Get() *MergePdfRequest {
	return v.value
}

func (v *NullableMergePdfRequest) Set(val *MergePdfRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMergePdfRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMergePdfRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergePdfRequest(val *MergePdfRequest) *NullableMergePdfRequest {
	return &NullableMergePdfRequest{value: val, isSet: true}
}

func (v NullableMergePdfRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergePdfRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


