/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)

// AppRoutersV1PdfToolsExportType the model 'AppRoutersV1PdfToolsExportType'
type AppRoutersV1PdfToolsExportType string

// List of app__routers__v1__pdf_tools__ExportType
const (
	URL AppRoutersV1PdfToolsExportType = "url"
	BINARY AppRoutersV1PdfToolsExportType = "binary"
)

// All allowed values of AppRoutersV1PdfToolsExportType enum
var AllowedAppRoutersV1PdfToolsExportTypeEnumValues = []AppRoutersV1PdfToolsExportType{
	"url",
	"binary",
}

func (v *AppRoutersV1PdfToolsExportType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppRoutersV1PdfToolsExportType(value)
	for _, existing := range AllowedAppRoutersV1PdfToolsExportTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppRoutersV1PdfToolsExportType", value)
}

// NewAppRoutersV1PdfToolsExportTypeFromValue returns a pointer to a valid AppRoutersV1PdfToolsExportType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppRoutersV1PdfToolsExportTypeFromValue(v string) (*AppRoutersV1PdfToolsExportType, error) {
	ev := AppRoutersV1PdfToolsExportType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppRoutersV1PdfToolsExportType: valid values are %v", v, AllowedAppRoutersV1PdfToolsExportTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppRoutersV1PdfToolsExportType) IsValid() bool {
	for _, existing := range AllowedAppRoutersV1PdfToolsExportTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to app__routers__v1__pdf_tools__ExportType value
func (v AppRoutersV1PdfToolsExportType) Ptr() *AppRoutersV1PdfToolsExportType {
	return &v
}

type NullableAppRoutersV1PdfToolsExportType struct {
	value *AppRoutersV1PdfToolsExportType
	isSet bool
}

func (v NullableAppRoutersV1PdfToolsExportType) Get() *AppRoutersV1PdfToolsExportType {
	return v.value
}

func (v *NullableAppRoutersV1PdfToolsExportType) Set(val *AppRoutersV1PdfToolsExportType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRoutersV1PdfToolsExportType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRoutersV1PdfToolsExportType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRoutersV1PdfToolsExportType(val *AppRoutersV1PdfToolsExportType) *NullableAppRoutersV1PdfToolsExportType {
	return &NullableAppRoutersV1PdfToolsExportType{value: val, isSet: true}
}

func (v NullableAppRoutersV1PdfToolsExportType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRoutersV1PdfToolsExportType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

