/*
TemplateFox API

Generate PDFs from HTML templates via API. Design once, generate thousands.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the S3SuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3SuccessResponse{}

// S3SuccessResponse Generic success response for S3 operations
type S3SuccessResponse struct {
	// Whether the operation succeeded
	Success bool `json:"success"`
}

type _S3SuccessResponse S3SuccessResponse

// NewS3SuccessResponse instantiates a new S3SuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3SuccessResponse(success bool) *S3SuccessResponse {
	this := S3SuccessResponse{}
	this.Success = success
	return &this
}

// NewS3SuccessResponseWithDefaults instantiates a new S3SuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3SuccessResponseWithDefaults() *S3SuccessResponse {
	this := S3SuccessResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *S3SuccessResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *S3SuccessResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *S3SuccessResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o S3SuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3SuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *S3SuccessResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3SuccessResponse := _S3SuccessResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3SuccessResponse)

	if err != nil {
		return err
	}

	*o = S3SuccessResponse(varS3SuccessResponse)

	return err
}

type NullableS3SuccessResponse struct {
	value *S3SuccessResponse
	isSet bool
}

func (v NullableS3SuccessResponse) Get() *S3SuccessResponse {
	return v.value
}

func (v *NullableS3SuccessResponse) Set(val *S3SuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableS3SuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableS3SuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3SuccessResponse(val *S3SuccessResponse) *NullableS3SuccessResponse {
	return &NullableS3SuccessResponse{value: val, isSet: true}
}

func (v NullableS3SuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3SuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


