/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
)

// checks if the UpdateVersionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateVersionRequest{}

// UpdateVersionRequest Request to update a version's tag or description. Send null to clear a field.
type UpdateVersionRequest struct {
	Tag NullableString `json:"tag,omitempty" validate:"regexp=^[a-z0-9][a-z0-9_-]{0,48}[a-z0-9]$"`
	Description NullableString `json:"description,omitempty"`
}

// NewUpdateVersionRequest instantiates a new UpdateVersionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateVersionRequest() *UpdateVersionRequest {
	this := UpdateVersionRequest{}
	return &this
}

// NewUpdateVersionRequestWithDefaults instantiates a new UpdateVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateVersionRequestWithDefaults() *UpdateVersionRequest {
	this := UpdateVersionRequest{}
	return &this
}

// GetTag returns the Tag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateVersionRequest) GetTag() string {
	if o == nil || IsNil(o.Tag.Get()) {
		var ret string
		return ret
	}
	return *o.Tag.Get()
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateVersionRequest) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tag.Get(), o.Tag.IsSet()
}

// HasTag returns a boolean if a field has been set.
func (o *UpdateVersionRequest) HasTag() bool {
	if o != nil && o.Tag.IsSet() {
		return true
	}

	return false
}

// SetTag gets a reference to the given NullableString and assigns it to the Tag field.
func (o *UpdateVersionRequest) SetTag(v string) {
	o.Tag.Set(&v)
}
// SetTagNil sets the value for Tag to be an explicit nil
func (o *UpdateVersionRequest) SetTagNil() {
	o.Tag.Set(nil)
}

// UnsetTag ensures that no value is present for Tag, not even an explicit nil
func (o *UpdateVersionRequest) UnsetTag() {
	o.Tag.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateVersionRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateVersionRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateVersionRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *UpdateVersionRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *UpdateVersionRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *UpdateVersionRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o UpdateVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateVersionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Tag.IsSet() {
		toSerialize["tag"] = o.Tag.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	return toSerialize, nil
}

type NullableUpdateVersionRequest struct {
	value *UpdateVersionRequest
	isSet bool
}

func (v NullableUpdateVersionRequest) Get() *UpdateVersionRequest {
	return v.value
}

func (v *NullableUpdateVersionRequest) Set(val *UpdateVersionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVersionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVersionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVersionRequest(val *UpdateVersionRequest) *NullableUpdateVersionRequest {
	return &NullableUpdateVersionRequest{value: val, isSet: true}
}

func (v NullableUpdateVersionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVersionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


