/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
)

// checks if the PdfInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PdfInput{}

// PdfInput Either pdf_url (HTTPS) or pdf_base64 — exactly one.
type PdfInput struct {
	PdfUrl NullableString `json:"pdf_url,omitempty"`
	PdfBase64 NullableString `json:"pdf_base64,omitempty"`
}

// NewPdfInput instantiates a new PdfInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPdfInput() *PdfInput {
	this := PdfInput{}
	return &this
}

// NewPdfInputWithDefaults instantiates a new PdfInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPdfInputWithDefaults() *PdfInput {
	this := PdfInput{}
	return &this
}

// GetPdfUrl returns the PdfUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PdfInput) GetPdfUrl() string {
	if o == nil || IsNil(o.PdfUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PdfUrl.Get()
}

// GetPdfUrlOk returns a tuple with the PdfUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdfInput) GetPdfUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfUrl.Get(), o.PdfUrl.IsSet()
}

// HasPdfUrl returns a boolean if a field has been set.
func (o *PdfInput) HasPdfUrl() bool {
	if o != nil && o.PdfUrl.IsSet() {
		return true
	}

	return false
}

// SetPdfUrl gets a reference to the given NullableString and assigns it to the PdfUrl field.
func (o *PdfInput) SetPdfUrl(v string) {
	o.PdfUrl.Set(&v)
}
// SetPdfUrlNil sets the value for PdfUrl to be an explicit nil
func (o *PdfInput) SetPdfUrlNil() {
	o.PdfUrl.Set(nil)
}

// UnsetPdfUrl ensures that no value is present for PdfUrl, not even an explicit nil
func (o *PdfInput) UnsetPdfUrl() {
	o.PdfUrl.Unset()
}

// GetPdfBase64 returns the PdfBase64 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PdfInput) GetPdfBase64() string {
	if o == nil || IsNil(o.PdfBase64.Get()) {
		var ret string
		return ret
	}
	return *o.PdfBase64.Get()
}

// GetPdfBase64Ok returns a tuple with the PdfBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdfInput) GetPdfBase64Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfBase64.Get(), o.PdfBase64.IsSet()
}

// HasPdfBase64 returns a boolean if a field has been set.
func (o *PdfInput) HasPdfBase64() bool {
	if o != nil && o.PdfBase64.IsSet() {
		return true
	}

	return false
}

// SetPdfBase64 gets a reference to the given NullableString and assigns it to the PdfBase64 field.
func (o *PdfInput) SetPdfBase64(v string) {
	o.PdfBase64.Set(&v)
}
// SetPdfBase64Nil sets the value for PdfBase64 to be an explicit nil
func (o *PdfInput) SetPdfBase64Nil() {
	o.PdfBase64.Set(nil)
}

// UnsetPdfBase64 ensures that no value is present for PdfBase64, not even an explicit nil
func (o *PdfInput) UnsetPdfBase64() {
	o.PdfBase64.Unset()
}

func (o PdfInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PdfInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PdfUrl.IsSet() {
		toSerialize["pdf_url"] = o.PdfUrl.Get()
	}
	if o.PdfBase64.IsSet() {
		toSerialize["pdf_base64"] = o.PdfBase64.Get()
	}
	return toSerialize, nil
}

type NullablePdfInput struct {
	value *PdfInput
	isSet bool
}

func (v NullablePdfInput) Get() *PdfInput {
	return v.value
}

func (v *NullablePdfInput) Set(val *PdfInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePdfInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePdfInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdfInput(val *PdfInput) *NullablePdfInput {
	return &NullablePdfInput{value: val, isSet: true}
}

func (v NullablePdfInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdfInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


