/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAgentTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentTemplateRequest{}

// CreateAgentTemplateRequest struct for CreateAgentTemplateRequest
type CreateAgentTemplateRequest struct {
	// What the template should look like and which layers it needs, in natural language.
	Instructions string `json:"instructions"`
	// Template name
	Name string `json:"name"`
	Preset NullableString `json:"preset,omitempty"`
	Width NullableInt32 `json:"width,omitempty"`
	Height NullableInt32 `json:"height,omitempty"`
	Brand NullableBrandInputs `json:"brand,omitempty"`
}

type _CreateAgentTemplateRequest CreateAgentTemplateRequest

// NewCreateAgentTemplateRequest instantiates a new CreateAgentTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentTemplateRequest(instructions string, name string) *CreateAgentTemplateRequest {
	this := CreateAgentTemplateRequest{}
	this.Instructions = instructions
	this.Name = name
	return &this
}

// NewCreateAgentTemplateRequestWithDefaults instantiates a new CreateAgentTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentTemplateRequestWithDefaults() *CreateAgentTemplateRequest {
	this := CreateAgentTemplateRequest{}
	return &this
}

// GetInstructions returns the Instructions field value
func (o *CreateAgentTemplateRequest) GetInstructions() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value
// and a boolean to check if the value has been set.
func (o *CreateAgentTemplateRequest) GetInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instructions, true
}

// SetInstructions sets field value
func (o *CreateAgentTemplateRequest) SetInstructions(v string) {
	o.Instructions = v
}

// GetName returns the Name field value
func (o *CreateAgentTemplateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAgentTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAgentTemplateRequest) SetName(v string) {
	o.Name = v
}

// GetPreset returns the Preset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAgentTemplateRequest) GetPreset() string {
	if o == nil || IsNil(o.Preset.Get()) {
		var ret string
		return ret
	}
	return *o.Preset.Get()
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAgentTemplateRequest) GetPresetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Preset.Get(), o.Preset.IsSet()
}

// HasPreset returns a boolean if a field has been set.
func (o *CreateAgentTemplateRequest) HasPreset() bool {
	if o != nil && o.Preset.IsSet() {
		return true
	}

	return false
}

// SetPreset gets a reference to the given NullableString and assigns it to the Preset field.
func (o *CreateAgentTemplateRequest) SetPreset(v string) {
	o.Preset.Set(&v)
}
// SetPresetNil sets the value for Preset to be an explicit nil
func (o *CreateAgentTemplateRequest) SetPresetNil() {
	o.Preset.Set(nil)
}

// UnsetPreset ensures that no value is present for Preset, not even an explicit nil
func (o *CreateAgentTemplateRequest) UnsetPreset() {
	o.Preset.Unset()
}

// GetWidth returns the Width field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAgentTemplateRequest) GetWidth() int32 {
	if o == nil || IsNil(o.Width.Get()) {
		var ret int32
		return ret
	}
	return *o.Width.Get()
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAgentTemplateRequest) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Width.Get(), o.Width.IsSet()
}

// HasWidth returns a boolean if a field has been set.
func (o *CreateAgentTemplateRequest) HasWidth() bool {
	if o != nil && o.Width.IsSet() {
		return true
	}

	return false
}

// SetWidth gets a reference to the given NullableInt32 and assigns it to the Width field.
func (o *CreateAgentTemplateRequest) SetWidth(v int32) {
	o.Width.Set(&v)
}
// SetWidthNil sets the value for Width to be an explicit nil
func (o *CreateAgentTemplateRequest) SetWidthNil() {
	o.Width.Set(nil)
}

// UnsetWidth ensures that no value is present for Width, not even an explicit nil
func (o *CreateAgentTemplateRequest) UnsetWidth() {
	o.Width.Unset()
}

// GetHeight returns the Height field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAgentTemplateRequest) GetHeight() int32 {
	if o == nil || IsNil(o.Height.Get()) {
		var ret int32
		return ret
	}
	return *o.Height.Get()
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAgentTemplateRequest) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Height.Get(), o.Height.IsSet()
}

// HasHeight returns a boolean if a field has been set.
func (o *CreateAgentTemplateRequest) HasHeight() bool {
	if o != nil && o.Height.IsSet() {
		return true
	}

	return false
}

// SetHeight gets a reference to the given NullableInt32 and assigns it to the Height field.
func (o *CreateAgentTemplateRequest) SetHeight(v int32) {
	o.Height.Set(&v)
}
// SetHeightNil sets the value for Height to be an explicit nil
func (o *CreateAgentTemplateRequest) SetHeightNil() {
	o.Height.Set(nil)
}

// UnsetHeight ensures that no value is present for Height, not even an explicit nil
func (o *CreateAgentTemplateRequest) UnsetHeight() {
	o.Height.Unset()
}

// GetBrand returns the Brand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAgentTemplateRequest) GetBrand() BrandInputs {
	if o == nil || IsNil(o.Brand.Get()) {
		var ret BrandInputs
		return ret
	}
	return *o.Brand.Get()
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAgentTemplateRequest) GetBrandOk() (*BrandInputs, bool) {
	if o == nil {
		return nil, false
	}
	return o.Brand.Get(), o.Brand.IsSet()
}

// HasBrand returns a boolean if a field has been set.
func (o *CreateAgentTemplateRequest) HasBrand() bool {
	if o != nil && o.Brand.IsSet() {
		return true
	}

	return false
}

// SetBrand gets a reference to the given NullableBrandInputs and assigns it to the Brand field.
func (o *CreateAgentTemplateRequest) SetBrand(v BrandInputs) {
	o.Brand.Set(&v)
}
// SetBrandNil sets the value for Brand to be an explicit nil
func (o *CreateAgentTemplateRequest) SetBrandNil() {
	o.Brand.Set(nil)
}

// UnsetBrand ensures that no value is present for Brand, not even an explicit nil
func (o *CreateAgentTemplateRequest) UnsetBrand() {
	o.Brand.Unset()
}

func (o CreateAgentTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instructions"] = o.Instructions
	toSerialize["name"] = o.Name
	if o.Preset.IsSet() {
		toSerialize["preset"] = o.Preset.Get()
	}
	if o.Width.IsSet() {
		toSerialize["width"] = o.Width.Get()
	}
	if o.Height.IsSet() {
		toSerialize["height"] = o.Height.Get()
	}
	if o.Brand.IsSet() {
		toSerialize["brand"] = o.Brand.Get()
	}
	return toSerialize, nil
}

func (o *CreateAgentTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instructions",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAgentTemplateRequest := _CreateAgentTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAgentTemplateRequest)

	if err != nil {
		return err
	}

	*o = CreateAgentTemplateRequest(varCreateAgentTemplateRequest)

	return err
}

type NullableCreateAgentTemplateRequest struct {
	value *CreateAgentTemplateRequest
	isSet bool
}

func (v NullableCreateAgentTemplateRequest) Get() *CreateAgentTemplateRequest {
	return v.value
}

func (v *NullableCreateAgentTemplateRequest) Set(val *CreateAgentTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentTemplateRequest(val *CreateAgentTemplateRequest) *NullableCreateAgentTemplateRequest {
	return &NullableCreateAgentTemplateRequest{value: val, isSet: true}
}

func (v NullableCreateAgentTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


