/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateLayer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateLayer{}

// TemplateLayer An addressable layer of a template (modifications API)
type TemplateLayer struct {
	// Layer name — the value to use in `modifications[].name`
	Name string `json:"name"`
	// HTML tag of the element
	Tag string `json:"tag"`
	// Layer type: `background`, `image`, `text` or `shape`
	Type string `json:"type"`
	CurrentText NullableString `json:"current_text,omitempty"`
	// Modification fields that apply to this layer
	Modifiable []string `json:"modifiable"`
}

type _TemplateLayer TemplateLayer

// NewTemplateLayer instantiates a new TemplateLayer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateLayer(name string, tag string, type_ string, modifiable []string) *TemplateLayer {
	this := TemplateLayer{}
	this.Name = name
	this.Tag = tag
	this.Type = type_
	this.Modifiable = modifiable
	return &this
}

// NewTemplateLayerWithDefaults instantiates a new TemplateLayer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateLayerWithDefaults() *TemplateLayer {
	this := TemplateLayer{}
	return &this
}

// GetName returns the Name field value
func (o *TemplateLayer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TemplateLayer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplateLayer) SetName(v string) {
	o.Name = v
}

// GetTag returns the Tag field value
func (o *TemplateLayer) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *TemplateLayer) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *TemplateLayer) SetTag(v string) {
	o.Tag = v
}

// GetType returns the Type field value
func (o *TemplateLayer) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TemplateLayer) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TemplateLayer) SetType(v string) {
	o.Type = v
}

// GetCurrentText returns the CurrentText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateLayer) GetCurrentText() string {
	if o == nil || IsNil(o.CurrentText.Get()) {
		var ret string
		return ret
	}
	return *o.CurrentText.Get()
}

// GetCurrentTextOk returns a tuple with the CurrentText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateLayer) GetCurrentTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentText.Get(), o.CurrentText.IsSet()
}

// HasCurrentText returns a boolean if a field has been set.
func (o *TemplateLayer) HasCurrentText() bool {
	if o != nil && o.CurrentText.IsSet() {
		return true
	}

	return false
}

// SetCurrentText gets a reference to the given NullableString and assigns it to the CurrentText field.
func (o *TemplateLayer) SetCurrentText(v string) {
	o.CurrentText.Set(&v)
}
// SetCurrentTextNil sets the value for CurrentText to be an explicit nil
func (o *TemplateLayer) SetCurrentTextNil() {
	o.CurrentText.Set(nil)
}

// UnsetCurrentText ensures that no value is present for CurrentText, not even an explicit nil
func (o *TemplateLayer) UnsetCurrentText() {
	o.CurrentText.Unset()
}

// GetModifiable returns the Modifiable field value
func (o *TemplateLayer) GetModifiable() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Modifiable
}

// GetModifiableOk returns a tuple with the Modifiable field value
// and a boolean to check if the value has been set.
func (o *TemplateLayer) GetModifiableOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Modifiable, true
}

// SetModifiable sets field value
func (o *TemplateLayer) SetModifiable(v []string) {
	o.Modifiable = v
}

func (o TemplateLayer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateLayer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["tag"] = o.Tag
	toSerialize["type"] = o.Type
	if o.CurrentText.IsSet() {
		toSerialize["current_text"] = o.CurrentText.Get()
	}
	toSerialize["modifiable"] = o.Modifiable
	return toSerialize, nil
}

func (o *TemplateLayer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"tag",
		"type",
		"modifiable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateLayer := _TemplateLayer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateLayer)

	if err != nil {
		return err
	}

	*o = TemplateLayer(varTemplateLayer)

	return err
}

type NullableTemplateLayer struct {
	value *TemplateLayer
	isSet bool
}

func (v NullableTemplateLayer) Get() *TemplateLayer {
	return v.value
}

func (v *NullableTemplateLayer) Set(val *TemplateLayer) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateLayer) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateLayer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateLayer(val *TemplateLayer) *NullableTemplateLayer {
	return &NullableTemplateLayer{value: val, isSet: true}
}

func (v NullableTemplateLayer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateLayer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


