/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateFieldSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateFieldSpec{}

// TemplateFieldSpec Spec for array item fields
type TemplateFieldSpec struct {
	// Field name
	Name string `json:"name"`
	// Field label
	Label string `json:"label"`
	// Field type: text, number
	Type *string `json:"type,omitempty"`
}

type _TemplateFieldSpec TemplateFieldSpec

// NewTemplateFieldSpec instantiates a new TemplateFieldSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateFieldSpec(name string, label string) *TemplateFieldSpec {
	this := TemplateFieldSpec{}
	this.Name = name
	this.Label = label
	var type_ string = "text"
	this.Type = &type_
	return &this
}

// NewTemplateFieldSpecWithDefaults instantiates a new TemplateFieldSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateFieldSpecWithDefaults() *TemplateFieldSpec {
	this := TemplateFieldSpec{}
	var type_ string = "text"
	this.Type = &type_
	return &this
}

// GetName returns the Name field value
func (o *TemplateFieldSpec) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TemplateFieldSpec) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplateFieldSpec) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *TemplateFieldSpec) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *TemplateFieldSpec) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *TemplateFieldSpec) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TemplateFieldSpec) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateFieldSpec) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TemplateFieldSpec) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TemplateFieldSpec) SetType(v string) {
	o.Type = &v
}

func (o TemplateFieldSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateFieldSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["label"] = o.Label
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *TemplateFieldSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateFieldSpec := _TemplateFieldSpec{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateFieldSpec)

	if err != nil {
		return err
	}

	*o = TemplateFieldSpec(varTemplateFieldSpec)

	return err
}

type NullableTemplateFieldSpec struct {
	value *TemplateFieldSpec
	isSet bool
}

func (v NullableTemplateFieldSpec) Get() *TemplateFieldSpec {
	return v.value
}

func (v *NullableTemplateFieldSpec) Set(val *TemplateFieldSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateFieldSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateFieldSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateFieldSpec(val *TemplateFieldSpec) *NullableTemplateFieldSpec {
	return &NullableTemplateFieldSpec{value: val, isSet: true}
}

func (v NullableTemplateFieldSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateFieldSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


