/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)

// PdfVariant PDF variant for standards-compliant output (PDF/A).
type PdfVariant string

// List of PdfVariant
const (
	PDF_A_1B PdfVariant = "pdf/a-1b"
	PDF_A_2B PdfVariant = "pdf/a-2b"
	PDF_A_3B PdfVariant = "pdf/a-3b"
)

// All allowed values of PdfVariant enum
var AllowedPdfVariantEnumValues = []PdfVariant{
	"pdf/a-1b",
	"pdf/a-2b",
	"pdf/a-3b",
}

func (v *PdfVariant) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PdfVariant(value)
	for _, existing := range AllowedPdfVariantEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PdfVariant", value)
}

// NewPdfVariantFromValue returns a pointer to a valid PdfVariant
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPdfVariantFromValue(v string) (*PdfVariant, error) {
	ev := PdfVariant(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PdfVariant: valid values are %v", v, AllowedPdfVariantEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PdfVariant) IsValid() bool {
	for _, existing := range AllowedPdfVariantEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PdfVariant value
func (v PdfVariant) Ptr() *PdfVariant {
	return &v
}

type NullablePdfVariant struct {
	value *PdfVariant
	isSet bool
}

func (v NullablePdfVariant) Get() *PdfVariant {
	return v.value
}

func (v *NullablePdfVariant) Set(val *PdfVariant) {
	v.value = val
	v.isSet = true
}

func (v NullablePdfVariant) IsSet() bool {
	return v.isSet
}

func (v *NullablePdfVariant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdfVariant(val *PdfVariant) *NullablePdfVariant {
	return &NullablePdfVariant{value: val, isSet: true}
}

func (v NullablePdfVariant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdfVariant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

