/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccountInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountInfoResponse{}

// AccountInfoResponse Response for account info endpoint
type AccountInfoResponse struct {
	// Remaining credits
	Credits int32 `json:"credits"`
	Email NullableString `json:"email,omitempty"`
}

type _AccountInfoResponse AccountInfoResponse

// NewAccountInfoResponse instantiates a new AccountInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountInfoResponse(credits int32) *AccountInfoResponse {
	this := AccountInfoResponse{}
	this.Credits = credits
	return &this
}

// NewAccountInfoResponseWithDefaults instantiates a new AccountInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountInfoResponseWithDefaults() *AccountInfoResponse {
	this := AccountInfoResponse{}
	return &this
}

// GetCredits returns the Credits field value
func (o *AccountInfoResponse) GetCredits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
func (o *AccountInfoResponse) GetCreditsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credits, true
}

// SetCredits sets field value
func (o *AccountInfoResponse) SetCredits(v int32) {
	o.Credits = v
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccountInfoResponse) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccountInfoResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *AccountInfoResponse) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *AccountInfoResponse) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *AccountInfoResponse) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *AccountInfoResponse) UnsetEmail() {
	o.Email.Unset()
}

func (o AccountInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credits"] = o.Credits
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	return toSerialize, nil
}

func (o *AccountInfoResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountInfoResponse := _AccountInfoResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountInfoResponse)

	if err != nil {
		return err
	}

	*o = AccountInfoResponse(varAccountInfoResponse)

	return err
}

type NullableAccountInfoResponse struct {
	value *AccountInfoResponse
	isSet bool
}

func (v NullableAccountInfoResponse) Get() *AccountInfoResponse {
	return v.value
}

func (v *NullableAccountInfoResponse) Set(val *AccountInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountInfoResponse(val *AccountInfoResponse) *NullableAccountInfoResponse {
	return &NullableAccountInfoResponse{value: val, isSet: true}
}

func (v NullableAccountInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


