/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VersionsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionsListResponse{}

// VersionsListResponse Response for versions list
type VersionsListResponse struct {
	Versions []VersionItem `json:"versions"`
}

type _VersionsListResponse VersionsListResponse

// NewVersionsListResponse instantiates a new VersionsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionsListResponse(versions []VersionItem) *VersionsListResponse {
	this := VersionsListResponse{}
	this.Versions = versions
	return &this
}

// NewVersionsListResponseWithDefaults instantiates a new VersionsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionsListResponseWithDefaults() *VersionsListResponse {
	this := VersionsListResponse{}
	return &this
}

// GetVersions returns the Versions field value
func (o *VersionsListResponse) GetVersions() []VersionItem {
	if o == nil {
		var ret []VersionItem
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *VersionsListResponse) GetVersionsOk() ([]VersionItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Versions, true
}

// SetVersions sets field value
func (o *VersionsListResponse) SetVersions(v []VersionItem) {
	o.Versions = v
}

func (o VersionsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versions"] = o.Versions
	return toSerialize, nil
}

func (o *VersionsListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVersionsListResponse := _VersionsListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVersionsListResponse)

	if err != nil {
		return err
	}

	*o = VersionsListResponse(varVersionsListResponse)

	return err
}

type NullableVersionsListResponse struct {
	value *VersionsListResponse
	isSet bool
}

func (v NullableVersionsListResponse) Get() *VersionsListResponse {
	return v.value
}

func (v *NullableVersionsListResponse) Set(val *VersionsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionsListResponse(val *VersionsListResponse) *NullableVersionsListResponse {
	return &NullableVersionsListResponse{value: val, isSet: true}
}

func (v NullableVersionsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


