/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReviseAgentTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviseAgentTemplateRequest{}

// ReviseAgentTemplateRequest struct for ReviseAgentTemplateRequest
type ReviseAgentTemplateRequest struct {
	// Natural-language feedback on the current template.
	Feedback string `json:"feedback"`
	Brand NullableBrandInputs `json:"brand,omitempty"`
}

type _ReviseAgentTemplateRequest ReviseAgentTemplateRequest

// NewReviseAgentTemplateRequest instantiates a new ReviseAgentTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviseAgentTemplateRequest(feedback string) *ReviseAgentTemplateRequest {
	this := ReviseAgentTemplateRequest{}
	this.Feedback = feedback
	return &this
}

// NewReviseAgentTemplateRequestWithDefaults instantiates a new ReviseAgentTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviseAgentTemplateRequestWithDefaults() *ReviseAgentTemplateRequest {
	this := ReviseAgentTemplateRequest{}
	return &this
}

// GetFeedback returns the Feedback field value
func (o *ReviseAgentTemplateRequest) GetFeedback() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Feedback
}

// GetFeedbackOk returns a tuple with the Feedback field value
// and a boolean to check if the value has been set.
func (o *ReviseAgentTemplateRequest) GetFeedbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Feedback, true
}

// SetFeedback sets field value
func (o *ReviseAgentTemplateRequest) SetFeedback(v string) {
	o.Feedback = v
}

// GetBrand returns the Brand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviseAgentTemplateRequest) GetBrand() BrandInputs {
	if o == nil || IsNil(o.Brand.Get()) {
		var ret BrandInputs
		return ret
	}
	return *o.Brand.Get()
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviseAgentTemplateRequest) GetBrandOk() (*BrandInputs, bool) {
	if o == nil {
		return nil, false
	}
	return o.Brand.Get(), o.Brand.IsSet()
}

// HasBrand returns a boolean if a field has been set.
func (o *ReviseAgentTemplateRequest) HasBrand() bool {
	if o != nil && o.Brand.IsSet() {
		return true
	}

	return false
}

// SetBrand gets a reference to the given NullableBrandInputs and assigns it to the Brand field.
func (o *ReviseAgentTemplateRequest) SetBrand(v BrandInputs) {
	o.Brand.Set(&v)
}
// SetBrandNil sets the value for Brand to be an explicit nil
func (o *ReviseAgentTemplateRequest) SetBrandNil() {
	o.Brand.Set(nil)
}

// UnsetBrand ensures that no value is present for Brand, not even an explicit nil
func (o *ReviseAgentTemplateRequest) UnsetBrand() {
	o.Brand.Unset()
}

func (o ReviseAgentTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviseAgentTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["feedback"] = o.Feedback
	if o.Brand.IsSet() {
		toSerialize["brand"] = o.Brand.Get()
	}
	return toSerialize, nil
}

func (o *ReviseAgentTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"feedback",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReviseAgentTemplateRequest := _ReviseAgentTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReviseAgentTemplateRequest)

	if err != nil {
		return err
	}

	*o = ReviseAgentTemplateRequest(varReviseAgentTemplateRequest)

	return err
}

type NullableReviseAgentTemplateRequest struct {
	value *ReviseAgentTemplateRequest
	isSet bool
}

func (v NullableReviseAgentTemplateRequest) Get() *ReviseAgentTemplateRequest {
	return v.value
}

func (v *NullableReviseAgentTemplateRequest) Set(val *ReviseAgentTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReviseAgentTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReviseAgentTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviseAgentTemplateRequest(val *ReviseAgentTemplateRequest) *NullableReviseAgentTemplateRequest {
	return &NullableReviseAgentTemplateRequest{value: val, isSet: true}
}

func (v NullableReviseAgentTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviseAgentTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


