/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
)

// checks if the BrandInputs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrandInputs{}

// BrandInputs Optional brand constraints passed to the agent.
type BrandInputs struct {
	// Brand colors as hex strings, e.g. ['#0C3C5F', '#E27D28']
	Colors []string `json:"colors,omitempty"`
	// Preferred font families. Non-built-in fonts are substituted with the closest built-in and noted in the result.
	Fonts []string `json:"fonts,omitempty"`
	// Public https:// URLs of assets (logo, photos) the agent may use.
	AssetUrls []string `json:"asset_urls,omitempty"`
}

// NewBrandInputs instantiates a new BrandInputs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrandInputs() *BrandInputs {
	this := BrandInputs{}
	return &this
}

// NewBrandInputsWithDefaults instantiates a new BrandInputs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrandInputsWithDefaults() *BrandInputs {
	this := BrandInputs{}
	return &this
}

// GetColors returns the Colors field value if set, zero value otherwise.
func (o *BrandInputs) GetColors() []string {
	if o == nil || IsNil(o.Colors) {
		var ret []string
		return ret
	}
	return o.Colors
}

// GetColorsOk returns a tuple with the Colors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandInputs) GetColorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Colors) {
		return nil, false
	}
	return o.Colors, true
}

// HasColors returns a boolean if a field has been set.
func (o *BrandInputs) HasColors() bool {
	if o != nil && !IsNil(o.Colors) {
		return true
	}

	return false
}

// SetColors gets a reference to the given []string and assigns it to the Colors field.
func (o *BrandInputs) SetColors(v []string) {
	o.Colors = v
}

// GetFonts returns the Fonts field value if set, zero value otherwise.
func (o *BrandInputs) GetFonts() []string {
	if o == nil || IsNil(o.Fonts) {
		var ret []string
		return ret
	}
	return o.Fonts
}

// GetFontsOk returns a tuple with the Fonts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandInputs) GetFontsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fonts) {
		return nil, false
	}
	return o.Fonts, true
}

// HasFonts returns a boolean if a field has been set.
func (o *BrandInputs) HasFonts() bool {
	if o != nil && !IsNil(o.Fonts) {
		return true
	}

	return false
}

// SetFonts gets a reference to the given []string and assigns it to the Fonts field.
func (o *BrandInputs) SetFonts(v []string) {
	o.Fonts = v
}

// GetAssetUrls returns the AssetUrls field value if set, zero value otherwise.
func (o *BrandInputs) GetAssetUrls() []string {
	if o == nil || IsNil(o.AssetUrls) {
		var ret []string
		return ret
	}
	return o.AssetUrls
}

// GetAssetUrlsOk returns a tuple with the AssetUrls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandInputs) GetAssetUrlsOk() ([]string, bool) {
	if o == nil || IsNil(o.AssetUrls) {
		return nil, false
	}
	return o.AssetUrls, true
}

// HasAssetUrls returns a boolean if a field has been set.
func (o *BrandInputs) HasAssetUrls() bool {
	if o != nil && !IsNil(o.AssetUrls) {
		return true
	}

	return false
}

// SetAssetUrls gets a reference to the given []string and assigns it to the AssetUrls field.
func (o *BrandInputs) SetAssetUrls(v []string) {
	o.AssetUrls = v
}

func (o BrandInputs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrandInputs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Colors) {
		toSerialize["colors"] = o.Colors
	}
	if !IsNil(o.Fonts) {
		toSerialize["fonts"] = o.Fonts
	}
	if !IsNil(o.AssetUrls) {
		toSerialize["asset_urls"] = o.AssetUrls
	}
	return toSerialize, nil
}

type NullableBrandInputs struct {
	value *BrandInputs
	isSet bool
}

func (v NullableBrandInputs) Get() *BrandInputs {
	return v.value
}

func (v *NullableBrandInputs) Set(val *BrandInputs) {
	v.value = val
	v.isSet = true
}

func (v NullableBrandInputs) IsSet() bool {
	return v.isSet
}

func (v *NullableBrandInputs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrandInputs(val *BrandInputs) *NullableBrandInputs {
	return &NullableBrandInputs{value: val, isSet: true}
}

func (v NullableBrandInputs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrandInputs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


