/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)


// Spec For array fields: spec defining the structure of each item
type Spec struct {
	TemplateFieldSpec *TemplateFieldSpec
	ArrayOfTemplateFieldSpec *[]TemplateFieldSpec
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Spec) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into TemplateFieldSpec
	err = json.Unmarshal(data, &dst.TemplateFieldSpec);
	if err == nil {
		jsonTemplateFieldSpec, _ := json.Marshal(dst.TemplateFieldSpec)
		if string(jsonTemplateFieldSpec) == "{}" { // empty struct
			dst.TemplateFieldSpec = nil
		} else {
			return nil // data stored in dst.TemplateFieldSpec, return on the first match
		}
	} else {
		dst.TemplateFieldSpec = nil
	}

	// try to unmarshal JSON data into ArrayOfTemplateFieldSpec
	err = json.Unmarshal(data, &dst.ArrayOfTemplateFieldSpec);
	if err == nil {
		jsonArrayOfTemplateFieldSpec, _ := json.Marshal(dst.ArrayOfTemplateFieldSpec)
		if string(jsonArrayOfTemplateFieldSpec) == "{}" { // empty struct
			dst.ArrayOfTemplateFieldSpec = nil
		} else {
			return nil // data stored in dst.ArrayOfTemplateFieldSpec, return on the first match
		}
	} else {
		dst.ArrayOfTemplateFieldSpec = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Spec)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Spec) MarshalJSON() ([]byte, error) {
	if src.TemplateFieldSpec != nil {
		return json.Marshal(&src.TemplateFieldSpec)
	}

	if src.ArrayOfTemplateFieldSpec != nil {
		return json.Marshal(&src.ArrayOfTemplateFieldSpec)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableSpec struct {
	value *Spec
	isSet bool
}

func (v NullableSpec) Get() *Spec {
	return v.value
}

func (v *NullableSpec) Set(val *Spec) {
	v.value = val
	v.isSet = true
}

func (v NullableSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpec(val *Spec) *NullableSpec {
	return &NullableSpec{value: val, isSet: true}
}

func (v NullableSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


