/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)

// AppRoutersV1PdfExportType PDF export type options
type AppRoutersV1PdfExportType string

// List of app__routers__v1__pdf__ExportType
const (
	URL AppRoutersV1PdfExportType = "url"
	BINARY AppRoutersV1PdfExportType = "binary"
)

// All allowed values of AppRoutersV1PdfExportType enum
var AllowedAppRoutersV1PdfExportTypeEnumValues = []AppRoutersV1PdfExportType{
	"url",
	"binary",
}

func (v *AppRoutersV1PdfExportType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppRoutersV1PdfExportType(value)
	for _, existing := range AllowedAppRoutersV1PdfExportTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppRoutersV1PdfExportType", value)
}

// NewAppRoutersV1PdfExportTypeFromValue returns a pointer to a valid AppRoutersV1PdfExportType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppRoutersV1PdfExportTypeFromValue(v string) (*AppRoutersV1PdfExportType, error) {
	ev := AppRoutersV1PdfExportType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppRoutersV1PdfExportType: valid values are %v", v, AllowedAppRoutersV1PdfExportTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppRoutersV1PdfExportType) IsValid() bool {
	for _, existing := range AllowedAppRoutersV1PdfExportTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to app__routers__v1__pdf__ExportType value
func (v AppRoutersV1PdfExportType) Ptr() *AppRoutersV1PdfExportType {
	return &v
}

type NullableAppRoutersV1PdfExportType struct {
	value *AppRoutersV1PdfExportType
	isSet bool
}

func (v NullableAppRoutersV1PdfExportType) Get() *AppRoutersV1PdfExportType {
	return v.value
}

func (v *NullableAppRoutersV1PdfExportType) Set(val *AppRoutersV1PdfExportType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRoutersV1PdfExportType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRoutersV1PdfExportType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRoutersV1PdfExportType(val *AppRoutersV1PdfExportType) *NullableAppRoutersV1PdfExportType {
	return &NullableAppRoutersV1PdfExportType{value: val, isSet: true}
}

func (v NullableAppRoutersV1PdfExportType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRoutersV1PdfExportType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

