/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateImageResponse{}

// CreateImageResponse Response for URL export type
type CreateImageResponse struct {
	// Signed URL to download the image (expires after specified time)
	Url string `json:"url"`
	// Filename of the generated image
	Filename string `json:"filename"`
	// Remaining credits after this request
	CreditsRemaining int32 `json:"credits_remaining"`
	// Seconds until the signed URL expires
	ExpiresIn int32 `json:"expires_in"`
	Warnings []string `json:"warnings,omitempty"`
}

type _CreateImageResponse CreateImageResponse

// NewCreateImageResponse instantiates a new CreateImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateImageResponse(url string, filename string, creditsRemaining int32, expiresIn int32) *CreateImageResponse {
	this := CreateImageResponse{}
	this.Url = url
	this.Filename = filename
	this.CreditsRemaining = creditsRemaining
	this.ExpiresIn = expiresIn
	return &this
}

// NewCreateImageResponseWithDefaults instantiates a new CreateImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateImageResponseWithDefaults() *CreateImageResponse {
	this := CreateImageResponse{}
	return &this
}

// GetUrl returns the Url field value
func (o *CreateImageResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateImageResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateImageResponse) SetUrl(v string) {
	o.Url = v
}

// GetFilename returns the Filename field value
func (o *CreateImageResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *CreateImageResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *CreateImageResponse) SetFilename(v string) {
	o.Filename = v
}

// GetCreditsRemaining returns the CreditsRemaining field value
func (o *CreateImageResponse) GetCreditsRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsRemaining
}

// GetCreditsRemainingOk returns a tuple with the CreditsRemaining field value
// and a boolean to check if the value has been set.
func (o *CreateImageResponse) GetCreditsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsRemaining, true
}

// SetCreditsRemaining sets field value
func (o *CreateImageResponse) SetCreditsRemaining(v int32) {
	o.CreditsRemaining = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *CreateImageResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *CreateImageResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *CreateImageResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateImageResponse) GetWarnings() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateImageResponse) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *CreateImageResponse) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *CreateImageResponse) SetWarnings(v []string) {
	o.Warnings = v
}

func (o CreateImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["filename"] = o.Filename
	toSerialize["credits_remaining"] = o.CreditsRemaining
	toSerialize["expires_in"] = o.ExpiresIn
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *CreateImageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"filename",
		"credits_remaining",
		"expires_in",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateImageResponse := _CreateImageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateImageResponse)

	if err != nil {
		return err
	}

	*o = CreateImageResponse(varCreateImageResponse)

	return err
}

type NullableCreateImageResponse struct {
	value *CreateImageResponse
	isSet bool
}

func (v NullableCreateImageResponse) Get() *CreateImageResponse {
	return v.value
}

func (v *NullableCreateImageResponse) Set(val *CreateImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateImageResponse(val *CreateImageResponse) *NullableCreateImageResponse {
	return &NullableCreateImageResponse{value: val, isSet: true}
}

func (v NullableCreateImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


