/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExtractPdfPagesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExtractPdfPagesRequest{}

// ExtractPdfPagesRequest struct for ExtractPdfPagesRequest
type ExtractPdfPagesRequest struct {
	// `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
	ExportType *AppRoutersV1PdfToolsExportType `json:"export_type,omitempty"`
	// URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
	Expiration *int32 `json:"expiration,omitempty"`
	Filename NullableString `json:"filename,omitempty" validate:"regexp=^[a-zA-Z0-9_\\\\-\\\\.]+$"`
	PdfUrl NullableString `json:"pdf_url,omitempty"`
	PdfBase64 NullableString `json:"pdf_base64,omitempty"`
	// 1-indexed page selection. Supports ranges and singles separated by commas, e.g. `1-3, 5, 7-9`. Order is preserved (`5,1,3` outputs those 3 pages in that order).
	Pages string `json:"pages"`
}

type _ExtractPdfPagesRequest ExtractPdfPagesRequest

// NewExtractPdfPagesRequest instantiates a new ExtractPdfPagesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtractPdfPagesRequest(pages string) *ExtractPdfPagesRequest {
	this := ExtractPdfPagesRequest{}
	var exportType AppRoutersV1PdfToolsExportType = URL
	this.ExportType = &exportType
	var expiration int32 = 86400
	this.Expiration = &expiration
	this.Pages = pages
	return &this
}

// NewExtractPdfPagesRequestWithDefaults instantiates a new ExtractPdfPagesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtractPdfPagesRequestWithDefaults() *ExtractPdfPagesRequest {
	this := ExtractPdfPagesRequest{}
	var exportType AppRoutersV1PdfToolsExportType = URL
	this.ExportType = &exportType
	var expiration int32 = 86400
	this.Expiration = &expiration
	return &this
}

// GetExportType returns the ExportType field value if set, zero value otherwise.
func (o *ExtractPdfPagesRequest) GetExportType() AppRoutersV1PdfToolsExportType {
	if o == nil || IsNil(o.ExportType) {
		var ret AppRoutersV1PdfToolsExportType
		return ret
	}
	return *o.ExportType
}

// GetExportTypeOk returns a tuple with the ExportType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtractPdfPagesRequest) GetExportTypeOk() (*AppRoutersV1PdfToolsExportType, bool) {
	if o == nil || IsNil(o.ExportType) {
		return nil, false
	}
	return o.ExportType, true
}

// HasExportType returns a boolean if a field has been set.
func (o *ExtractPdfPagesRequest) HasExportType() bool {
	if o != nil && !IsNil(o.ExportType) {
		return true
	}

	return false
}

// SetExportType gets a reference to the given AppRoutersV1PdfToolsExportType and assigns it to the ExportType field.
func (o *ExtractPdfPagesRequest) SetExportType(v AppRoutersV1PdfToolsExportType) {
	o.ExportType = &v
}

// GetExpiration returns the Expiration field value if set, zero value otherwise.
func (o *ExtractPdfPagesRequest) GetExpiration() int32 {
	if o == nil || IsNil(o.Expiration) {
		var ret int32
		return ret
	}
	return *o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtractPdfPagesRequest) GetExpirationOk() (*int32, bool) {
	if o == nil || IsNil(o.Expiration) {
		return nil, false
	}
	return o.Expiration, true
}

// HasExpiration returns a boolean if a field has been set.
func (o *ExtractPdfPagesRequest) HasExpiration() bool {
	if o != nil && !IsNil(o.Expiration) {
		return true
	}

	return false
}

// SetExpiration gets a reference to the given int32 and assigns it to the Expiration field.
func (o *ExtractPdfPagesRequest) SetExpiration(v int32) {
	o.Expiration = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExtractPdfPagesRequest) GetFilename() string {
	if o == nil || IsNil(o.Filename.Get()) {
		var ret string
		return ret
	}
	return *o.Filename.Get()
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExtractPdfPagesRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filename.Get(), o.Filename.IsSet()
}

// HasFilename returns a boolean if a field has been set.
func (o *ExtractPdfPagesRequest) HasFilename() bool {
	if o != nil && o.Filename.IsSet() {
		return true
	}

	return false
}

// SetFilename gets a reference to the given NullableString and assigns it to the Filename field.
func (o *ExtractPdfPagesRequest) SetFilename(v string) {
	o.Filename.Set(&v)
}
// SetFilenameNil sets the value for Filename to be an explicit nil
func (o *ExtractPdfPagesRequest) SetFilenameNil() {
	o.Filename.Set(nil)
}

// UnsetFilename ensures that no value is present for Filename, not even an explicit nil
func (o *ExtractPdfPagesRequest) UnsetFilename() {
	o.Filename.Unset()
}

// GetPdfUrl returns the PdfUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExtractPdfPagesRequest) GetPdfUrl() string {
	if o == nil || IsNil(o.PdfUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PdfUrl.Get()
}

// GetPdfUrlOk returns a tuple with the PdfUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExtractPdfPagesRequest) GetPdfUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfUrl.Get(), o.PdfUrl.IsSet()
}

// HasPdfUrl returns a boolean if a field has been set.
func (o *ExtractPdfPagesRequest) HasPdfUrl() bool {
	if o != nil && o.PdfUrl.IsSet() {
		return true
	}

	return false
}

// SetPdfUrl gets a reference to the given NullableString and assigns it to the PdfUrl field.
func (o *ExtractPdfPagesRequest) SetPdfUrl(v string) {
	o.PdfUrl.Set(&v)
}
// SetPdfUrlNil sets the value for PdfUrl to be an explicit nil
func (o *ExtractPdfPagesRequest) SetPdfUrlNil() {
	o.PdfUrl.Set(nil)
}

// UnsetPdfUrl ensures that no value is present for PdfUrl, not even an explicit nil
func (o *ExtractPdfPagesRequest) UnsetPdfUrl() {
	o.PdfUrl.Unset()
}

// GetPdfBase64 returns the PdfBase64 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExtractPdfPagesRequest) GetPdfBase64() string {
	if o == nil || IsNil(o.PdfBase64.Get()) {
		var ret string
		return ret
	}
	return *o.PdfBase64.Get()
}

// GetPdfBase64Ok returns a tuple with the PdfBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExtractPdfPagesRequest) GetPdfBase64Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfBase64.Get(), o.PdfBase64.IsSet()
}

// HasPdfBase64 returns a boolean if a field has been set.
func (o *ExtractPdfPagesRequest) HasPdfBase64() bool {
	if o != nil && o.PdfBase64.IsSet() {
		return true
	}

	return false
}

// SetPdfBase64 gets a reference to the given NullableString and assigns it to the PdfBase64 field.
func (o *ExtractPdfPagesRequest) SetPdfBase64(v string) {
	o.PdfBase64.Set(&v)
}
// SetPdfBase64Nil sets the value for PdfBase64 to be an explicit nil
func (o *ExtractPdfPagesRequest) SetPdfBase64Nil() {
	o.PdfBase64.Set(nil)
}

// UnsetPdfBase64 ensures that no value is present for PdfBase64, not even an explicit nil
func (o *ExtractPdfPagesRequest) UnsetPdfBase64() {
	o.PdfBase64.Unset()
}

// GetPages returns the Pages field value
func (o *ExtractPdfPagesRequest) GetPages() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
func (o *ExtractPdfPagesRequest) GetPagesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pages, true
}

// SetPages sets field value
func (o *ExtractPdfPagesRequest) SetPages(v string) {
	o.Pages = v
}

func (o ExtractPdfPagesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExtractPdfPagesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExportType) {
		toSerialize["export_type"] = o.ExportType
	}
	if !IsNil(o.Expiration) {
		toSerialize["expiration"] = o.Expiration
	}
	if o.Filename.IsSet() {
		toSerialize["filename"] = o.Filename.Get()
	}
	if o.PdfUrl.IsSet() {
		toSerialize["pdf_url"] = o.PdfUrl.Get()
	}
	if o.PdfBase64.IsSet() {
		toSerialize["pdf_base64"] = o.PdfBase64.Get()
	}
	toSerialize["pages"] = o.Pages
	return toSerialize, nil
}

func (o *ExtractPdfPagesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExtractPdfPagesRequest := _ExtractPdfPagesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExtractPdfPagesRequest)

	if err != nil {
		return err
	}

	*o = ExtractPdfPagesRequest(varExtractPdfPagesRequest)

	return err
}

type NullableExtractPdfPagesRequest struct {
	value *ExtractPdfPagesRequest
	isSet bool
}

func (v NullableExtractPdfPagesRequest) Get() *ExtractPdfPagesRequest {
	return v.value
}

func (v *NullableExtractPdfPagesRequest) Set(val *ExtractPdfPagesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExtractPdfPagesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExtractPdfPagesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtractPdfPagesRequest(val *ExtractPdfPagesRequest) *NullableExtractPdfPagesRequest {
	return &NullableExtractPdfPagesRequest{value: val, isSet: true}
}

func (v NullableExtractPdfPagesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtractPdfPagesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


