/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.11.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Modification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Modification{}

// Modification A single element modification, addressed by layer name.
type Modification struct {
	// Name of the layer to modify (set via the editor's Layers panel). Matched against the element's `data-layer-name`, falling back to its `id`.
	Name string `json:"name"`
	Text NullableString `json:"text,omitempty"`
	ImageUrl NullableString `json:"image_url,omitempty" validate:"regexp=^https?:\\/\\/"`
	Color NullableString `json:"color,omitempty"`
	Background NullableString `json:"background,omitempty"`
	Hidden NullableBool `json:"hidden,omitempty"`
}

type _Modification Modification

// NewModification instantiates a new Modification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModification(name string) *Modification {
	this := Modification{}
	this.Name = name
	return &this
}

// NewModificationWithDefaults instantiates a new Modification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModificationWithDefaults() *Modification {
	this := Modification{}
	return &this
}

// GetName returns the Name field value
func (o *Modification) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Modification) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Modification) SetName(v string) {
	o.Name = v
}

// GetText returns the Text field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Modification) GetText() string {
	if o == nil || IsNil(o.Text.Get()) {
		var ret string
		return ret
	}
	return *o.Text.Get()
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Modification) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Text.Get(), o.Text.IsSet()
}

// HasText returns a boolean if a field has been set.
func (o *Modification) HasText() bool {
	if o != nil && o.Text.IsSet() {
		return true
	}

	return false
}

// SetText gets a reference to the given NullableString and assigns it to the Text field.
func (o *Modification) SetText(v string) {
	o.Text.Set(&v)
}
// SetTextNil sets the value for Text to be an explicit nil
func (o *Modification) SetTextNil() {
	o.Text.Set(nil)
}

// UnsetText ensures that no value is present for Text, not even an explicit nil
func (o *Modification) UnsetText() {
	o.Text.Unset()
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Modification) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ImageUrl.Get()
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Modification) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageUrl.Get(), o.ImageUrl.IsSet()
}

// HasImageUrl returns a boolean if a field has been set.
func (o *Modification) HasImageUrl() bool {
	if o != nil && o.ImageUrl.IsSet() {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given NullableString and assigns it to the ImageUrl field.
func (o *Modification) SetImageUrl(v string) {
	o.ImageUrl.Set(&v)
}
// SetImageUrlNil sets the value for ImageUrl to be an explicit nil
func (o *Modification) SetImageUrlNil() {
	o.ImageUrl.Set(nil)
}

// UnsetImageUrl ensures that no value is present for ImageUrl, not even an explicit nil
func (o *Modification) UnsetImageUrl() {
	o.ImageUrl.Unset()
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Modification) GetColor() string {
	if o == nil || IsNil(o.Color.Get()) {
		var ret string
		return ret
	}
	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Modification) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// HasColor returns a boolean if a field has been set.
func (o *Modification) HasColor() bool {
	if o != nil && o.Color.IsSet() {
		return true
	}

	return false
}

// SetColor gets a reference to the given NullableString and assigns it to the Color field.
func (o *Modification) SetColor(v string) {
	o.Color.Set(&v)
}
// SetColorNil sets the value for Color to be an explicit nil
func (o *Modification) SetColorNil() {
	o.Color.Set(nil)
}

// UnsetColor ensures that no value is present for Color, not even an explicit nil
func (o *Modification) UnsetColor() {
	o.Color.Unset()
}

// GetBackground returns the Background field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Modification) GetBackground() string {
	if o == nil || IsNil(o.Background.Get()) {
		var ret string
		return ret
	}
	return *o.Background.Get()
}

// GetBackgroundOk returns a tuple with the Background field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Modification) GetBackgroundOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Background.Get(), o.Background.IsSet()
}

// HasBackground returns a boolean if a field has been set.
func (o *Modification) HasBackground() bool {
	if o != nil && o.Background.IsSet() {
		return true
	}

	return false
}

// SetBackground gets a reference to the given NullableString and assigns it to the Background field.
func (o *Modification) SetBackground(v string) {
	o.Background.Set(&v)
}
// SetBackgroundNil sets the value for Background to be an explicit nil
func (o *Modification) SetBackgroundNil() {
	o.Background.Set(nil)
}

// UnsetBackground ensures that no value is present for Background, not even an explicit nil
func (o *Modification) UnsetBackground() {
	o.Background.Unset()
}

// GetHidden returns the Hidden field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Modification) GetHidden() bool {
	if o == nil || IsNil(o.Hidden.Get()) {
		var ret bool
		return ret
	}
	return *o.Hidden.Get()
}

// GetHiddenOk returns a tuple with the Hidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Modification) GetHiddenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hidden.Get(), o.Hidden.IsSet()
}

// HasHidden returns a boolean if a field has been set.
func (o *Modification) HasHidden() bool {
	if o != nil && o.Hidden.IsSet() {
		return true
	}

	return false
}

// SetHidden gets a reference to the given NullableBool and assigns it to the Hidden field.
func (o *Modification) SetHidden(v bool) {
	o.Hidden.Set(&v)
}
// SetHiddenNil sets the value for Hidden to be an explicit nil
func (o *Modification) SetHiddenNil() {
	o.Hidden.Set(nil)
}

// UnsetHidden ensures that no value is present for Hidden, not even an explicit nil
func (o *Modification) UnsetHidden() {
	o.Hidden.Unset()
}

func (o Modification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Modification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Text.IsSet() {
		toSerialize["text"] = o.Text.Get()
	}
	if o.ImageUrl.IsSet() {
		toSerialize["image_url"] = o.ImageUrl.Get()
	}
	if o.Color.IsSet() {
		toSerialize["color"] = o.Color.Get()
	}
	if o.Background.IsSet() {
		toSerialize["background"] = o.Background.Get()
	}
	if o.Hidden.IsSet() {
		toSerialize["hidden"] = o.Hidden.Get()
	}
	return toSerialize, nil
}

func (o *Modification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModification := _Modification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModification)

	if err != nil {
		return err
	}

	*o = Modification(varModification)

	return err
}

type NullableModification struct {
	value *Modification
	isSet bool
}

func (v NullableModification) Get() *Modification {
	return v.value
}

func (v *NullableModification) Set(val *Modification) {
	v.value = val
	v.isSet = true
}

func (v NullableModification) IsSet() bool {
	return v.isSet
}

func (v *NullableModification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModification(val *Modification) *NullableModification {
	return &NullableModification{value: val, isSet: true}
}

func (v NullableModification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


