/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobStatusResponse{}

// JobStatusResponse Response for job status query
type JobStatusResponse struct {
	// Job ID
	Id string `json:"id"`
	// Current job status
	Status JobStatus `json:"status"`
	// Template used for generation
	TemplateId string `json:"template_id"`
	// Export type (url)
	ExportType string `json:"export_type"`
	Filename NullableString `json:"filename,omitempty"`
	// Whether S3 storage was requested
	StoreS3 bool `json:"store_s3"`
	// Job creation timestamp (ISO 8601)
	CreatedAt string `json:"created_at"`
	// Last update timestamp (ISO 8601)
	UpdatedAt string `json:"updated_at"`
	CompletedAt NullableString `json:"completed_at,omitempty"`
	ResultUrl NullableString `json:"result_url,omitempty"`
	ResultFilename NullableString `json:"result_filename,omitempty"`
	ResultExpiresAt NullableString `json:"result_expires_at,omitempty"`
	ResultS3Bucket NullableString `json:"result_s3_bucket,omitempty"`
	ResultS3Key NullableString `json:"result_s3_key,omitempty"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
	ErrorCode NullableString `json:"error_code,omitempty"`
}

type _JobStatusResponse JobStatusResponse

// NewJobStatusResponse instantiates a new JobStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobStatusResponse(id string, status JobStatus, templateId string, exportType string, storeS3 bool, createdAt string, updatedAt string) *JobStatusResponse {
	this := JobStatusResponse{}
	this.Id = id
	this.Status = status
	this.TemplateId = templateId
	this.ExportType = exportType
	this.StoreS3 = storeS3
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewJobStatusResponseWithDefaults instantiates a new JobStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobStatusResponseWithDefaults() *JobStatusResponse {
	this := JobStatusResponse{}
	return &this
}

// GetId returns the Id field value
func (o *JobStatusResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JobStatusResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JobStatusResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *JobStatusResponse) GetStatus() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *JobStatusResponse) GetStatusOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *JobStatusResponse) SetStatus(v JobStatus) {
	o.Status = v
}

// GetTemplateId returns the TemplateId field value
func (o *JobStatusResponse) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *JobStatusResponse) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *JobStatusResponse) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetExportType returns the ExportType field value
func (o *JobStatusResponse) GetExportType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExportType
}

// GetExportTypeOk returns a tuple with the ExportType field value
// and a boolean to check if the value has been set.
func (o *JobStatusResponse) GetExportTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExportType, true
}

// SetExportType sets field value
func (o *JobStatusResponse) SetExportType(v string) {
	o.ExportType = v
}

// GetFilename returns the Filename field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetFilename() string {
	if o == nil || IsNil(o.Filename.Get()) {
		var ret string
		return ret
	}
	return *o.Filename.Get()
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filename.Get(), o.Filename.IsSet()
}

// HasFilename returns a boolean if a field has been set.
func (o *JobStatusResponse) HasFilename() bool {
	if o != nil && o.Filename.IsSet() {
		return true
	}

	return false
}

// SetFilename gets a reference to the given NullableString and assigns it to the Filename field.
func (o *JobStatusResponse) SetFilename(v string) {
	o.Filename.Set(&v)
}
// SetFilenameNil sets the value for Filename to be an explicit nil
func (o *JobStatusResponse) SetFilenameNil() {
	o.Filename.Set(nil)
}

// UnsetFilename ensures that no value is present for Filename, not even an explicit nil
func (o *JobStatusResponse) UnsetFilename() {
	o.Filename.Unset()
}

// GetStoreS3 returns the StoreS3 field value
func (o *JobStatusResponse) GetStoreS3() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StoreS3
}

// GetStoreS3Ok returns a tuple with the StoreS3 field value
// and a boolean to check if the value has been set.
func (o *JobStatusResponse) GetStoreS3Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoreS3, true
}

// SetStoreS3 sets field value
func (o *JobStatusResponse) SetStoreS3(v bool) {
	o.StoreS3 = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *JobStatusResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *JobStatusResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *JobStatusResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *JobStatusResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *JobStatusResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *JobStatusResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *JobStatusResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableString and assigns it to the CompletedAt field.
func (o *JobStatusResponse) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *JobStatusResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *JobStatusResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetResultUrl returns the ResultUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetResultUrl() string {
	if o == nil || IsNil(o.ResultUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ResultUrl.Get()
}

// GetResultUrlOk returns a tuple with the ResultUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetResultUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultUrl.Get(), o.ResultUrl.IsSet()
}

// HasResultUrl returns a boolean if a field has been set.
func (o *JobStatusResponse) HasResultUrl() bool {
	if o != nil && o.ResultUrl.IsSet() {
		return true
	}

	return false
}

// SetResultUrl gets a reference to the given NullableString and assigns it to the ResultUrl field.
func (o *JobStatusResponse) SetResultUrl(v string) {
	o.ResultUrl.Set(&v)
}
// SetResultUrlNil sets the value for ResultUrl to be an explicit nil
func (o *JobStatusResponse) SetResultUrlNil() {
	o.ResultUrl.Set(nil)
}

// UnsetResultUrl ensures that no value is present for ResultUrl, not even an explicit nil
func (o *JobStatusResponse) UnsetResultUrl() {
	o.ResultUrl.Unset()
}

// GetResultFilename returns the ResultFilename field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetResultFilename() string {
	if o == nil || IsNil(o.ResultFilename.Get()) {
		var ret string
		return ret
	}
	return *o.ResultFilename.Get()
}

// GetResultFilenameOk returns a tuple with the ResultFilename field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetResultFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultFilename.Get(), o.ResultFilename.IsSet()
}

// HasResultFilename returns a boolean if a field has been set.
func (o *JobStatusResponse) HasResultFilename() bool {
	if o != nil && o.ResultFilename.IsSet() {
		return true
	}

	return false
}

// SetResultFilename gets a reference to the given NullableString and assigns it to the ResultFilename field.
func (o *JobStatusResponse) SetResultFilename(v string) {
	o.ResultFilename.Set(&v)
}
// SetResultFilenameNil sets the value for ResultFilename to be an explicit nil
func (o *JobStatusResponse) SetResultFilenameNil() {
	o.ResultFilename.Set(nil)
}

// UnsetResultFilename ensures that no value is present for ResultFilename, not even an explicit nil
func (o *JobStatusResponse) UnsetResultFilename() {
	o.ResultFilename.Unset()
}

// GetResultExpiresAt returns the ResultExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetResultExpiresAt() string {
	if o == nil || IsNil(o.ResultExpiresAt.Get()) {
		var ret string
		return ret
	}
	return *o.ResultExpiresAt.Get()
}

// GetResultExpiresAtOk returns a tuple with the ResultExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetResultExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultExpiresAt.Get(), o.ResultExpiresAt.IsSet()
}

// HasResultExpiresAt returns a boolean if a field has been set.
func (o *JobStatusResponse) HasResultExpiresAt() bool {
	if o != nil && o.ResultExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetResultExpiresAt gets a reference to the given NullableString and assigns it to the ResultExpiresAt field.
func (o *JobStatusResponse) SetResultExpiresAt(v string) {
	o.ResultExpiresAt.Set(&v)
}
// SetResultExpiresAtNil sets the value for ResultExpiresAt to be an explicit nil
func (o *JobStatusResponse) SetResultExpiresAtNil() {
	o.ResultExpiresAt.Set(nil)
}

// UnsetResultExpiresAt ensures that no value is present for ResultExpiresAt, not even an explicit nil
func (o *JobStatusResponse) UnsetResultExpiresAt() {
	o.ResultExpiresAt.Unset()
}

// GetResultS3Bucket returns the ResultS3Bucket field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetResultS3Bucket() string {
	if o == nil || IsNil(o.ResultS3Bucket.Get()) {
		var ret string
		return ret
	}
	return *o.ResultS3Bucket.Get()
}

// GetResultS3BucketOk returns a tuple with the ResultS3Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetResultS3BucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultS3Bucket.Get(), o.ResultS3Bucket.IsSet()
}

// HasResultS3Bucket returns a boolean if a field has been set.
func (o *JobStatusResponse) HasResultS3Bucket() bool {
	if o != nil && o.ResultS3Bucket.IsSet() {
		return true
	}

	return false
}

// SetResultS3Bucket gets a reference to the given NullableString and assigns it to the ResultS3Bucket field.
func (o *JobStatusResponse) SetResultS3Bucket(v string) {
	o.ResultS3Bucket.Set(&v)
}
// SetResultS3BucketNil sets the value for ResultS3Bucket to be an explicit nil
func (o *JobStatusResponse) SetResultS3BucketNil() {
	o.ResultS3Bucket.Set(nil)
}

// UnsetResultS3Bucket ensures that no value is present for ResultS3Bucket, not even an explicit nil
func (o *JobStatusResponse) UnsetResultS3Bucket() {
	o.ResultS3Bucket.Unset()
}

// GetResultS3Key returns the ResultS3Key field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetResultS3Key() string {
	if o == nil || IsNil(o.ResultS3Key.Get()) {
		var ret string
		return ret
	}
	return *o.ResultS3Key.Get()
}

// GetResultS3KeyOk returns a tuple with the ResultS3Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetResultS3KeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultS3Key.Get(), o.ResultS3Key.IsSet()
}

// HasResultS3Key returns a boolean if a field has been set.
func (o *JobStatusResponse) HasResultS3Key() bool {
	if o != nil && o.ResultS3Key.IsSet() {
		return true
	}

	return false
}

// SetResultS3Key gets a reference to the given NullableString and assigns it to the ResultS3Key field.
func (o *JobStatusResponse) SetResultS3Key(v string) {
	o.ResultS3Key.Set(&v)
}
// SetResultS3KeyNil sets the value for ResultS3Key to be an explicit nil
func (o *JobStatusResponse) SetResultS3KeyNil() {
	o.ResultS3Key.Set(nil)
}

// UnsetResultS3Key ensures that no value is present for ResultS3Key, not even an explicit nil
func (o *JobStatusResponse) UnsetResultS3Key() {
	o.ResultS3Key.Unset()
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *JobStatusResponse) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *JobStatusResponse) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *JobStatusResponse) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *JobStatusResponse) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobStatusResponse) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobStatusResponse) GetErrorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *JobStatusResponse) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableString and assigns it to the ErrorCode field.
func (o *JobStatusResponse) SetErrorCode(v string) {
	o.ErrorCode.Set(&v)
}
// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *JobStatusResponse) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *JobStatusResponse) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

func (o JobStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["template_id"] = o.TemplateId
	toSerialize["export_type"] = o.ExportType
	if o.Filename.IsSet() {
		toSerialize["filename"] = o.Filename.Get()
	}
	toSerialize["store_s3"] = o.StoreS3
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if o.ResultUrl.IsSet() {
		toSerialize["result_url"] = o.ResultUrl.Get()
	}
	if o.ResultFilename.IsSet() {
		toSerialize["result_filename"] = o.ResultFilename.Get()
	}
	if o.ResultExpiresAt.IsSet() {
		toSerialize["result_expires_at"] = o.ResultExpiresAt.Get()
	}
	if o.ResultS3Bucket.IsSet() {
		toSerialize["result_s3_bucket"] = o.ResultS3Bucket.Get()
	}
	if o.ResultS3Key.IsSet() {
		toSerialize["result_s3_key"] = o.ResultS3Key.Get()
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	if o.ErrorCode.IsSet() {
		toSerialize["error_code"] = o.ErrorCode.Get()
	}
	return toSerialize, nil
}

func (o *JobStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"template_id",
		"export_type",
		"store_s3",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobStatusResponse := _JobStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobStatusResponse)

	if err != nil {
		return err
	}

	*o = JobStatusResponse(varJobStatusResponse)

	return err
}

type NullableJobStatusResponse struct {
	value *JobStatusResponse
	isSet bool
}

func (v NullableJobStatusResponse) Get() *JobStatusResponse {
	return v.value
}

func (v *NullableJobStatusResponse) Set(val *JobStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJobStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJobStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobStatusResponse(val *JobStatusResponse) *NullableJobStatusResponse {
	return &NullableJobStatusResponse{value: val, isSet: true}
}

func (v NullableJobStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


