/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetDefaultVersionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDefaultVersionRequest{}

// SetDefaultVersionRequest Request to set the default version
type SetDefaultVersionRequest struct {
	// Version number to set as default
	VersionNumber int32 `json:"version_number"`
}

type _SetDefaultVersionRequest SetDefaultVersionRequest

// NewSetDefaultVersionRequest instantiates a new SetDefaultVersionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDefaultVersionRequest(versionNumber int32) *SetDefaultVersionRequest {
	this := SetDefaultVersionRequest{}
	this.VersionNumber = versionNumber
	return &this
}

// NewSetDefaultVersionRequestWithDefaults instantiates a new SetDefaultVersionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDefaultVersionRequestWithDefaults() *SetDefaultVersionRequest {
	this := SetDefaultVersionRequest{}
	return &this
}

// GetVersionNumber returns the VersionNumber field value
func (o *SetDefaultVersionRequest) GetVersionNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VersionNumber
}

// GetVersionNumberOk returns a tuple with the VersionNumber field value
// and a boolean to check if the value has been set.
func (o *SetDefaultVersionRequest) GetVersionNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionNumber, true
}

// SetVersionNumber sets field value
func (o *SetDefaultVersionRequest) SetVersionNumber(v int32) {
	o.VersionNumber = v
}

func (o SetDefaultVersionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDefaultVersionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version_number"] = o.VersionNumber
	return toSerialize, nil
}

func (o *SetDefaultVersionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDefaultVersionRequest := _SetDefaultVersionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetDefaultVersionRequest)

	if err != nil {
		return err
	}

	*o = SetDefaultVersionRequest(varSetDefaultVersionRequest)

	return err
}

type NullableSetDefaultVersionRequest struct {
	value *SetDefaultVersionRequest
	isSet bool
}

func (v NullableSetDefaultVersionRequest) Get() *SetDefaultVersionRequest {
	return v.value
}

func (v *NullableSetDefaultVersionRequest) Set(val *SetDefaultVersionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDefaultVersionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDefaultVersionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDefaultVersionRequest(val *SetDefaultVersionRequest) *NullableSetDefaultVersionRequest {
	return &NullableSetDefaultVersionRequest{value: val, isSet: true}
}

func (v NullableSetDefaultVersionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDefaultVersionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


