/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAsyncPdfResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAsyncPdfResponse{}

// CreateAsyncPdfResponse Response for async PDF creation
type CreateAsyncPdfResponse struct {
	// Unique job identifier for status polling
	JobId string `json:"job_id"`
	// Initial job status (always 'pending')
	Status JobStatus `json:"status"`
	// Remaining credits after this request
	CreditsRemaining int32 `json:"credits_remaining"`
}

type _CreateAsyncPdfResponse CreateAsyncPdfResponse

// NewCreateAsyncPdfResponse instantiates a new CreateAsyncPdfResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAsyncPdfResponse(jobId string, status JobStatus, creditsRemaining int32) *CreateAsyncPdfResponse {
	this := CreateAsyncPdfResponse{}
	this.JobId = jobId
	this.Status = status
	this.CreditsRemaining = creditsRemaining
	return &this
}

// NewCreateAsyncPdfResponseWithDefaults instantiates a new CreateAsyncPdfResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAsyncPdfResponseWithDefaults() *CreateAsyncPdfResponse {
	this := CreateAsyncPdfResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *CreateAsyncPdfResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *CreateAsyncPdfResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *CreateAsyncPdfResponse) SetJobId(v string) {
	o.JobId = v
}

// GetStatus returns the Status field value
func (o *CreateAsyncPdfResponse) GetStatus() JobStatus {
	if o == nil {
		var ret JobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateAsyncPdfResponse) GetStatusOk() (*JobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateAsyncPdfResponse) SetStatus(v JobStatus) {
	o.Status = v
}

// GetCreditsRemaining returns the CreditsRemaining field value
func (o *CreateAsyncPdfResponse) GetCreditsRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsRemaining
}

// GetCreditsRemainingOk returns a tuple with the CreditsRemaining field value
// and a boolean to check if the value has been set.
func (o *CreateAsyncPdfResponse) GetCreditsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsRemaining, true
}

// SetCreditsRemaining sets field value
func (o *CreateAsyncPdfResponse) SetCreditsRemaining(v int32) {
	o.CreditsRemaining = v
}

func (o CreateAsyncPdfResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAsyncPdfResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	toSerialize["status"] = o.Status
	toSerialize["credits_remaining"] = o.CreditsRemaining
	return toSerialize, nil
}

func (o *CreateAsyncPdfResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
		"status",
		"credits_remaining",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAsyncPdfResponse := _CreateAsyncPdfResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAsyncPdfResponse)

	if err != nil {
		return err
	}

	*o = CreateAsyncPdfResponse(varCreateAsyncPdfResponse)

	return err
}

type NullableCreateAsyncPdfResponse struct {
	value *CreateAsyncPdfResponse
	isSet bool
}

func (v NullableCreateAsyncPdfResponse) Get() *CreateAsyncPdfResponse {
	return v.value
}

func (v *NullableCreateAsyncPdfResponse) Set(val *CreateAsyncPdfResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAsyncPdfResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAsyncPdfResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAsyncPdfResponse(val *CreateAsyncPdfResponse) *NullableCreateAsyncPdfResponse {
	return &NullableCreateAsyncPdfResponse{value: val, isSet: true}
}

func (v NullableCreateAsyncPdfResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAsyncPdfResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


