/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the S3TestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3TestResponse{}

// S3TestResponse Response for S3 connection test
type S3TestResponse struct {
	// Whether the connection test succeeded
	Success bool `json:"success"`
	// Test result message
	Message string `json:"message"`
}

type _S3TestResponse S3TestResponse

// NewS3TestResponse instantiates a new S3TestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3TestResponse(success bool, message string) *S3TestResponse {
	this := S3TestResponse{}
	this.Success = success
	this.Message = message
	return &this
}

// NewS3TestResponseWithDefaults instantiates a new S3TestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3TestResponseWithDefaults() *S3TestResponse {
	this := S3TestResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *S3TestResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *S3TestResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *S3TestResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *S3TestResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *S3TestResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *S3TestResponse) SetMessage(v string) {
	o.Message = v
}

func (o S3TestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3TestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *S3TestResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3TestResponse := _S3TestResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3TestResponse)

	if err != nil {
		return err
	}

	*o = S3TestResponse(varS3TestResponse)

	return err
}

type NullableS3TestResponse struct {
	value *S3TestResponse
	isSet bool
}

func (v NullableS3TestResponse) Get() *S3TestResponse {
	return v.value
}

func (v *NullableS3TestResponse) Set(val *S3TestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableS3TestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableS3TestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3TestResponse(val *S3TestResponse) *NullableS3TestResponse {
	return &NullableS3TestResponse{value: val, isSet: true}
}

func (v NullableS3TestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3TestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


