/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)

// AppRoutersV1DeliveryExportType Output delivery type options
type AppRoutersV1DeliveryExportType string

// List of app__routers__v1___delivery__ExportType
const (
	URL AppRoutersV1DeliveryExportType = "url"
	BINARY AppRoutersV1DeliveryExportType = "binary"
)

// All allowed values of AppRoutersV1DeliveryExportType enum
var AllowedAppRoutersV1DeliveryExportTypeEnumValues = []AppRoutersV1DeliveryExportType{
	"url",
	"binary",
}

func (v *AppRoutersV1DeliveryExportType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppRoutersV1DeliveryExportType(value)
	for _, existing := range AllowedAppRoutersV1DeliveryExportTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppRoutersV1DeliveryExportType", value)
}

// NewAppRoutersV1DeliveryExportTypeFromValue returns a pointer to a valid AppRoutersV1DeliveryExportType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppRoutersV1DeliveryExportTypeFromValue(v string) (*AppRoutersV1DeliveryExportType, error) {
	ev := AppRoutersV1DeliveryExportType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppRoutersV1DeliveryExportType: valid values are %v", v, AllowedAppRoutersV1DeliveryExportTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppRoutersV1DeliveryExportType) IsValid() bool {
	for _, existing := range AllowedAppRoutersV1DeliveryExportTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to app__routers__v1___delivery__ExportType value
func (v AppRoutersV1DeliveryExportType) Ptr() *AppRoutersV1DeliveryExportType {
	return &v
}

type NullableAppRoutersV1DeliveryExportType struct {
	value *AppRoutersV1DeliveryExportType
	isSet bool
}

func (v NullableAppRoutersV1DeliveryExportType) Get() *AppRoutersV1DeliveryExportType {
	return v.value
}

func (v *NullableAppRoutersV1DeliveryExportType) Set(val *AppRoutersV1DeliveryExportType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRoutersV1DeliveryExportType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRoutersV1DeliveryExportType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRoutersV1DeliveryExportType(val *AppRoutersV1DeliveryExportType) *NullableAppRoutersV1DeliveryExportType {
	return &NullableAppRoutersV1DeliveryExportType{value: val, isSet: true}
}

func (v NullableAppRoutersV1DeliveryExportType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRoutersV1DeliveryExportType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

