/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobListResponse{}

// JobListResponse Response for job list query
type JobListResponse struct {
	// List of jobs
	Jobs []JobStatusResponse `json:"jobs"`
	// Total number of jobs matching filter
	Total int32 `json:"total"`
	// Page size
	Limit int32 `json:"limit"`
	// Page offset
	Offset int32 `json:"offset"`
}

type _JobListResponse JobListResponse

// NewJobListResponse instantiates a new JobListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobListResponse(jobs []JobStatusResponse, total int32, limit int32, offset int32) *JobListResponse {
	this := JobListResponse{}
	this.Jobs = jobs
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewJobListResponseWithDefaults instantiates a new JobListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobListResponseWithDefaults() *JobListResponse {
	this := JobListResponse{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *JobListResponse) GetJobs() []JobStatusResponse {
	if o == nil {
		var ret []JobStatusResponse
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *JobListResponse) GetJobsOk() ([]JobStatusResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *JobListResponse) SetJobs(v []JobStatusResponse) {
	o.Jobs = v
}

// GetTotal returns the Total field value
func (o *JobListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *JobListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *JobListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *JobListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *JobListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *JobListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *JobListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *JobListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *JobListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o JobListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

func (o *JobListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
		"total",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobListResponse := _JobListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobListResponse)

	if err != nil {
		return err
	}

	*o = JobListResponse(varJobListResponse)

	return err
}

type NullableJobListResponse struct {
	value *JobListResponse
	isSet bool
}

func (v NullableJobListResponse) Get() *JobListResponse {
	return v.value
}

func (v *NullableJobListResponse) Set(val *JobListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJobListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJobListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobListResponse(val *JobListResponse) *NullableJobListResponse {
	return &NullableJobListResponse{value: val, isSet: true}
}

func (v NullableJobListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


