/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateLayersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateLayersResponse{}

// TemplateLayersResponse Response for template layers endpoint
type TemplateLayersResponse struct {
	Layers []TemplateLayer `json:"layers"`
	// Non-fatal issues (e.g. duplicate layer names)
	Warnings []string `json:"warnings,omitempty"`
}

type _TemplateLayersResponse TemplateLayersResponse

// NewTemplateLayersResponse instantiates a new TemplateLayersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateLayersResponse(layers []TemplateLayer) *TemplateLayersResponse {
	this := TemplateLayersResponse{}
	this.Layers = layers
	return &this
}

// NewTemplateLayersResponseWithDefaults instantiates a new TemplateLayersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateLayersResponseWithDefaults() *TemplateLayersResponse {
	this := TemplateLayersResponse{}
	return &this
}

// GetLayers returns the Layers field value
func (o *TemplateLayersResponse) GetLayers() []TemplateLayer {
	if o == nil {
		var ret []TemplateLayer
		return ret
	}

	return o.Layers
}

// GetLayersOk returns a tuple with the Layers field value
// and a boolean to check if the value has been set.
func (o *TemplateLayersResponse) GetLayersOk() ([]TemplateLayer, bool) {
	if o == nil {
		return nil, false
	}
	return o.Layers, true
}

// SetLayers sets field value
func (o *TemplateLayersResponse) SetLayers(v []TemplateLayer) {
	o.Layers = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *TemplateLayersResponse) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateLayersResponse) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *TemplateLayersResponse) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *TemplateLayersResponse) SetWarnings(v []string) {
	o.Warnings = v
}

func (o TemplateLayersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateLayersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["layers"] = o.Layers
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *TemplateLayersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"layers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateLayersResponse := _TemplateLayersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateLayersResponse)

	if err != nil {
		return err
	}

	*o = TemplateLayersResponse(varTemplateLayersResponse)

	return err
}

type NullableTemplateLayersResponse struct {
	value *TemplateLayersResponse
	isSet bool
}

func (v NullableTemplateLayersResponse) Get() *TemplateLayersResponse {
	return v.value
}

func (v *NullableTemplateLayersResponse) Set(val *TemplateLayersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateLayersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateLayersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateLayersResponse(val *TemplateLayersResponse) *NullableTemplateLayersResponse {
	return &NullableTemplateLayersResponse{value: val, isSet: true}
}

func (v NullableTemplateLayersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateLayersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


