/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
)

// checks if the RotatePdfRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotatePdfRequest{}

// RotatePdfRequest struct for RotatePdfRequest
type RotatePdfRequest struct {
	// `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes
	ExportType *AppRoutersV1PdfToolsExportType `json:"export_type,omitempty"`
	// URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.
	Expiration *int32 `json:"expiration,omitempty"`
	Filename NullableString `json:"filename,omitempty" validate:"regexp=^[a-zA-Z0-9_\\\\-\\\\.]+$"`
	PdfUrl NullableString `json:"pdf_url,omitempty"`
	PdfBase64 NullableString `json:"pdf_base64,omitempty"`
	Rotation NullableInt32 `json:"rotation,omitempty"`
	PageRotations map[string]int32 `json:"page_rotations,omitempty"`
}

// NewRotatePdfRequest instantiates a new RotatePdfRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotatePdfRequest() *RotatePdfRequest {
	this := RotatePdfRequest{}
	var exportType AppRoutersV1PdfToolsExportType = URL
	this.ExportType = &exportType
	var expiration int32 = 86400
	this.Expiration = &expiration
	return &this
}

// NewRotatePdfRequestWithDefaults instantiates a new RotatePdfRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotatePdfRequestWithDefaults() *RotatePdfRequest {
	this := RotatePdfRequest{}
	var exportType AppRoutersV1PdfToolsExportType = URL
	this.ExportType = &exportType
	var expiration int32 = 86400
	this.Expiration = &expiration
	return &this
}

// GetExportType returns the ExportType field value if set, zero value otherwise.
func (o *RotatePdfRequest) GetExportType() AppRoutersV1PdfToolsExportType {
	if o == nil || IsNil(o.ExportType) {
		var ret AppRoutersV1PdfToolsExportType
		return ret
	}
	return *o.ExportType
}

// GetExportTypeOk returns a tuple with the ExportType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatePdfRequest) GetExportTypeOk() (*AppRoutersV1PdfToolsExportType, bool) {
	if o == nil || IsNil(o.ExportType) {
		return nil, false
	}
	return o.ExportType, true
}

// HasExportType returns a boolean if a field has been set.
func (o *RotatePdfRequest) HasExportType() bool {
	if o != nil && !IsNil(o.ExportType) {
		return true
	}

	return false
}

// SetExportType gets a reference to the given AppRoutersV1PdfToolsExportType and assigns it to the ExportType field.
func (o *RotatePdfRequest) SetExportType(v AppRoutersV1PdfToolsExportType) {
	o.ExportType = &v
}

// GetExpiration returns the Expiration field value if set, zero value otherwise.
func (o *RotatePdfRequest) GetExpiration() int32 {
	if o == nil || IsNil(o.Expiration) {
		var ret int32
		return ret
	}
	return *o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatePdfRequest) GetExpirationOk() (*int32, bool) {
	if o == nil || IsNil(o.Expiration) {
		return nil, false
	}
	return o.Expiration, true
}

// HasExpiration returns a boolean if a field has been set.
func (o *RotatePdfRequest) HasExpiration() bool {
	if o != nil && !IsNil(o.Expiration) {
		return true
	}

	return false
}

// SetExpiration gets a reference to the given int32 and assigns it to the Expiration field.
func (o *RotatePdfRequest) SetExpiration(v int32) {
	o.Expiration = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RotatePdfRequest) GetFilename() string {
	if o == nil || IsNil(o.Filename.Get()) {
		var ret string
		return ret
	}
	return *o.Filename.Get()
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RotatePdfRequest) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filename.Get(), o.Filename.IsSet()
}

// HasFilename returns a boolean if a field has been set.
func (o *RotatePdfRequest) HasFilename() bool {
	if o != nil && o.Filename.IsSet() {
		return true
	}

	return false
}

// SetFilename gets a reference to the given NullableString and assigns it to the Filename field.
func (o *RotatePdfRequest) SetFilename(v string) {
	o.Filename.Set(&v)
}
// SetFilenameNil sets the value for Filename to be an explicit nil
func (o *RotatePdfRequest) SetFilenameNil() {
	o.Filename.Set(nil)
}

// UnsetFilename ensures that no value is present for Filename, not even an explicit nil
func (o *RotatePdfRequest) UnsetFilename() {
	o.Filename.Unset()
}

// GetPdfUrl returns the PdfUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RotatePdfRequest) GetPdfUrl() string {
	if o == nil || IsNil(o.PdfUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PdfUrl.Get()
}

// GetPdfUrlOk returns a tuple with the PdfUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RotatePdfRequest) GetPdfUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfUrl.Get(), o.PdfUrl.IsSet()
}

// HasPdfUrl returns a boolean if a field has been set.
func (o *RotatePdfRequest) HasPdfUrl() bool {
	if o != nil && o.PdfUrl.IsSet() {
		return true
	}

	return false
}

// SetPdfUrl gets a reference to the given NullableString and assigns it to the PdfUrl field.
func (o *RotatePdfRequest) SetPdfUrl(v string) {
	o.PdfUrl.Set(&v)
}
// SetPdfUrlNil sets the value for PdfUrl to be an explicit nil
func (o *RotatePdfRequest) SetPdfUrlNil() {
	o.PdfUrl.Set(nil)
}

// UnsetPdfUrl ensures that no value is present for PdfUrl, not even an explicit nil
func (o *RotatePdfRequest) UnsetPdfUrl() {
	o.PdfUrl.Unset()
}

// GetPdfBase64 returns the PdfBase64 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RotatePdfRequest) GetPdfBase64() string {
	if o == nil || IsNil(o.PdfBase64.Get()) {
		var ret string
		return ret
	}
	return *o.PdfBase64.Get()
}

// GetPdfBase64Ok returns a tuple with the PdfBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RotatePdfRequest) GetPdfBase64Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PdfBase64.Get(), o.PdfBase64.IsSet()
}

// HasPdfBase64 returns a boolean if a field has been set.
func (o *RotatePdfRequest) HasPdfBase64() bool {
	if o != nil && o.PdfBase64.IsSet() {
		return true
	}

	return false
}

// SetPdfBase64 gets a reference to the given NullableString and assigns it to the PdfBase64 field.
func (o *RotatePdfRequest) SetPdfBase64(v string) {
	o.PdfBase64.Set(&v)
}
// SetPdfBase64Nil sets the value for PdfBase64 to be an explicit nil
func (o *RotatePdfRequest) SetPdfBase64Nil() {
	o.PdfBase64.Set(nil)
}

// UnsetPdfBase64 ensures that no value is present for PdfBase64, not even an explicit nil
func (o *RotatePdfRequest) UnsetPdfBase64() {
	o.PdfBase64.Unset()
}

// GetRotation returns the Rotation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RotatePdfRequest) GetRotation() int32 {
	if o == nil || IsNil(o.Rotation.Get()) {
		var ret int32
		return ret
	}
	return *o.Rotation.Get()
}

// GetRotationOk returns a tuple with the Rotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RotatePdfRequest) GetRotationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rotation.Get(), o.Rotation.IsSet()
}

// HasRotation returns a boolean if a field has been set.
func (o *RotatePdfRequest) HasRotation() bool {
	if o != nil && o.Rotation.IsSet() {
		return true
	}

	return false
}

// SetRotation gets a reference to the given NullableInt32 and assigns it to the Rotation field.
func (o *RotatePdfRequest) SetRotation(v int32) {
	o.Rotation.Set(&v)
}
// SetRotationNil sets the value for Rotation to be an explicit nil
func (o *RotatePdfRequest) SetRotationNil() {
	o.Rotation.Set(nil)
}

// UnsetRotation ensures that no value is present for Rotation, not even an explicit nil
func (o *RotatePdfRequest) UnsetRotation() {
	o.Rotation.Unset()
}

// GetPageRotations returns the PageRotations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RotatePdfRequest) GetPageRotations() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}
	return o.PageRotations
}

// GetPageRotationsOk returns a tuple with the PageRotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RotatePdfRequest) GetPageRotationsOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.PageRotations) {
		return map[string]int32{}, false
	}
	return o.PageRotations, true
}

// HasPageRotations returns a boolean if a field has been set.
func (o *RotatePdfRequest) HasPageRotations() bool {
	if o != nil && !IsNil(o.PageRotations) {
		return true
	}

	return false
}

// SetPageRotations gets a reference to the given map[string]int32 and assigns it to the PageRotations field.
func (o *RotatePdfRequest) SetPageRotations(v map[string]int32) {
	o.PageRotations = v
}

func (o RotatePdfRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotatePdfRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExportType) {
		toSerialize["export_type"] = o.ExportType
	}
	if !IsNil(o.Expiration) {
		toSerialize["expiration"] = o.Expiration
	}
	if o.Filename.IsSet() {
		toSerialize["filename"] = o.Filename.Get()
	}
	if o.PdfUrl.IsSet() {
		toSerialize["pdf_url"] = o.PdfUrl.Get()
	}
	if o.PdfBase64.IsSet() {
		toSerialize["pdf_base64"] = o.PdfBase64.Get()
	}
	if o.Rotation.IsSet() {
		toSerialize["rotation"] = o.Rotation.Get()
	}
	if o.PageRotations != nil {
		toSerialize["page_rotations"] = o.PageRotations
	}
	return toSerialize, nil
}

type NullableRotatePdfRequest struct {
	value *RotatePdfRequest
	isSet bool
}

func (v NullableRotatePdfRequest) Get() *RotatePdfRequest {
	return v.value
}

func (v *NullableRotatePdfRequest) Set(val *RotatePdfRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotatePdfRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotatePdfRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotatePdfRequest(val *RotatePdfRequest) *NullableRotatePdfRequest {
	return &NullableRotatePdfRequest{value: val, isSet: true}
}

func (v NullableRotatePdfRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotatePdfRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


