/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Transaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Transaction{}

// Transaction Transaction record
type Transaction struct {
	// Unique transaction reference (UUID)
	TransactionRef string `json:"transaction_ref"`
	// Transaction type: PDFGEN, PURCHASE, REFUND, BONUS
	TransactionType string `json:"transaction_type"`
	TemplateId NullableString `json:"template_id,omitempty"`
	ExecTm NullableInt32 `json:"exec_tm,omitempty"`
	// Credits consumed (positive) or added (negative)
	Credits int32 `json:"credits"`
	// ISO 8601 timestamp
	CreatedAt string `json:"created_at"`
}

type _Transaction Transaction

// NewTransaction instantiates a new Transaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransaction(transactionRef string, transactionType string, credits int32, createdAt string) *Transaction {
	this := Transaction{}
	this.TransactionRef = transactionRef
	this.TransactionType = transactionType
	this.Credits = credits
	this.CreatedAt = createdAt
	return &this
}

// NewTransactionWithDefaults instantiates a new Transaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionWithDefaults() *Transaction {
	this := Transaction{}
	return &this
}

// GetTransactionRef returns the TransactionRef field value
func (o *Transaction) GetTransactionRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionRef
}

// GetTransactionRefOk returns a tuple with the TransactionRef field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetTransactionRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionRef, true
}

// SetTransactionRef sets field value
func (o *Transaction) SetTransactionRef(v string) {
	o.TransactionRef = v
}

// GetTransactionType returns the TransactionType field value
func (o *Transaction) GetTransactionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetTransactionTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionType, true
}

// SetTransactionType sets field value
func (o *Transaction) SetTransactionType(v string) {
	o.TransactionType = v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Transaction) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId.Get()) {
		var ret string
		return ret
	}
	return *o.TemplateId.Get()
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Transaction) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateId.Get(), o.TemplateId.IsSet()
}

// HasTemplateId returns a boolean if a field has been set.
func (o *Transaction) HasTemplateId() bool {
	if o != nil && o.TemplateId.IsSet() {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given NullableString and assigns it to the TemplateId field.
func (o *Transaction) SetTemplateId(v string) {
	o.TemplateId.Set(&v)
}
// SetTemplateIdNil sets the value for TemplateId to be an explicit nil
func (o *Transaction) SetTemplateIdNil() {
	o.TemplateId.Set(nil)
}

// UnsetTemplateId ensures that no value is present for TemplateId, not even an explicit nil
func (o *Transaction) UnsetTemplateId() {
	o.TemplateId.Unset()
}

// GetExecTm returns the ExecTm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Transaction) GetExecTm() int32 {
	if o == nil || IsNil(o.ExecTm.Get()) {
		var ret int32
		return ret
	}
	return *o.ExecTm.Get()
}

// GetExecTmOk returns a tuple with the ExecTm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Transaction) GetExecTmOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExecTm.Get(), o.ExecTm.IsSet()
}

// HasExecTm returns a boolean if a field has been set.
func (o *Transaction) HasExecTm() bool {
	if o != nil && o.ExecTm.IsSet() {
		return true
	}

	return false
}

// SetExecTm gets a reference to the given NullableInt32 and assigns it to the ExecTm field.
func (o *Transaction) SetExecTm(v int32) {
	o.ExecTm.Set(&v)
}
// SetExecTmNil sets the value for ExecTm to be an explicit nil
func (o *Transaction) SetExecTmNil() {
	o.ExecTm.Set(nil)
}

// UnsetExecTm ensures that no value is present for ExecTm, not even an explicit nil
func (o *Transaction) UnsetExecTm() {
	o.ExecTm.Unset()
}

// GetCredits returns the Credits field value
func (o *Transaction) GetCredits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetCreditsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credits, true
}

// SetCredits sets field value
func (o *Transaction) SetCredits(v int32) {
	o.Credits = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Transaction) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Transaction) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Transaction) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o Transaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Transaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_ref"] = o.TransactionRef
	toSerialize["transaction_type"] = o.TransactionType
	if o.TemplateId.IsSet() {
		toSerialize["template_id"] = o.TemplateId.Get()
	}
	if o.ExecTm.IsSet() {
		toSerialize["exec_tm"] = o.ExecTm.Get()
	}
	toSerialize["credits"] = o.Credits
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *Transaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_ref",
		"transaction_type",
		"credits",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransaction := _Transaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransaction)

	if err != nil {
		return err
	}

	*o = Transaction(varTransaction)

	return err
}

type NullableTransaction struct {
	value *Transaction
	isSet bool
}

func (v NullableTransaction) Get() *Transaction {
	return v.value
}

func (v *NullableTransaction) Set(val *Transaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransaction(val *Transaction) *NullableTransaction {
	return &NullableTransaction{value: val, isSet: true}
}

func (v NullableTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


