/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.1.1.dev2+gfe6303fdd.d20260209
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateField{}

// TemplateField Field definition for template variables (compatible with Zapier and Make.com)
type TemplateField struct {
	// Field key/identifier
	Key string `json:"key"`
	// Human-readable label
	Label string `json:"label"`
	// Field type: string, integer, number, boolean, array
	Type *string `json:"type,omitempty"`
	// Whether the field is required
	Required *bool `json:"required,omitempty"`
	HelpText NullableString `json:"helpText,omitempty"`
	Spec []TemplateFieldSpec `json:"spec,omitempty"`
}

type _TemplateField TemplateField

// NewTemplateField instantiates a new TemplateField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateField(key string, label string) *TemplateField {
	this := TemplateField{}
	this.Key = key
	this.Label = label
	var type_ string = "string"
	this.Type = &type_
	var required bool = false
	this.Required = &required
	return &this
}

// NewTemplateFieldWithDefaults instantiates a new TemplateField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateFieldWithDefaults() *TemplateField {
	this := TemplateField{}
	var type_ string = "string"
	this.Type = &type_
	var required bool = false
	this.Required = &required
	return &this
}

// GetKey returns the Key field value
func (o *TemplateField) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *TemplateField) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *TemplateField) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *TemplateField) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *TemplateField) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *TemplateField) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TemplateField) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TemplateField) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TemplateField) SetType(v string) {
	o.Type = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *TemplateField) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateField) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *TemplateField) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *TemplateField) SetRequired(v bool) {
	o.Required = &v
}

// GetHelpText returns the HelpText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateField) GetHelpText() string {
	if o == nil || IsNil(o.HelpText.Get()) {
		var ret string
		return ret
	}
	return *o.HelpText.Get()
}

// GetHelpTextOk returns a tuple with the HelpText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateField) GetHelpTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HelpText.Get(), o.HelpText.IsSet()
}

// HasHelpText returns a boolean if a field has been set.
func (o *TemplateField) HasHelpText() bool {
	if o != nil && o.HelpText.IsSet() {
		return true
	}

	return false
}

// SetHelpText gets a reference to the given NullableString and assigns it to the HelpText field.
func (o *TemplateField) SetHelpText(v string) {
	o.HelpText.Set(&v)
}
// SetHelpTextNil sets the value for HelpText to be an explicit nil
func (o *TemplateField) SetHelpTextNil() {
	o.HelpText.Set(nil)
}

// UnsetHelpText ensures that no value is present for HelpText, not even an explicit nil
func (o *TemplateField) UnsetHelpText() {
	o.HelpText.Unset()
}

// GetSpec returns the Spec field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateField) GetSpec() []TemplateFieldSpec {
	if o == nil {
		var ret []TemplateFieldSpec
		return ret
	}
	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateField) GetSpecOk() ([]TemplateFieldSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *TemplateField) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given []TemplateFieldSpec and assigns it to the Spec field.
func (o *TemplateField) SetSpec(v []TemplateFieldSpec) {
	o.Spec = v
}

func (o TemplateField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if o.HelpText.IsSet() {
		toSerialize["helpText"] = o.HelpText.Get()
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

func (o *TemplateField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateField := _TemplateField{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateField)

	if err != nil {
		return err
	}

	*o = TemplateField(varTemplateField)

	return err
}

type NullableTemplateField struct {
	value *TemplateField
	isSet bool
}

func (v NullableTemplateField) Get() *TemplateField {
	return v.value
}

func (v *NullableTemplateField) Set(val *TemplateField) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateField) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateField(val *TemplateField) *NullableTemplateField {
	return &NullableTemplateField{value: val, isSet: true}
}

func (v NullableTemplateField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


