/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PdfToolsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PdfToolsResponse{}

// PdfToolsResponse struct for PdfToolsResponse
type PdfToolsResponse struct {
	// Signed URL to download the PDF
	Url string `json:"url"`
	// Filename of the resulting PDF
	Filename string `json:"filename"`
	// Remaining credits after this request
	CreditsRemaining int32 `json:"credits_remaining"`
	// Seconds until the signed URL expires
	ExpiresIn int32 `json:"expires_in"`
}

type _PdfToolsResponse PdfToolsResponse

// NewPdfToolsResponse instantiates a new PdfToolsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPdfToolsResponse(url string, filename string, creditsRemaining int32, expiresIn int32) *PdfToolsResponse {
	this := PdfToolsResponse{}
	this.Url = url
	this.Filename = filename
	this.CreditsRemaining = creditsRemaining
	this.ExpiresIn = expiresIn
	return &this
}

// NewPdfToolsResponseWithDefaults instantiates a new PdfToolsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPdfToolsResponseWithDefaults() *PdfToolsResponse {
	this := PdfToolsResponse{}
	return &this
}

// GetUrl returns the Url field value
func (o *PdfToolsResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PdfToolsResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PdfToolsResponse) SetUrl(v string) {
	o.Url = v
}

// GetFilename returns the Filename field value
func (o *PdfToolsResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *PdfToolsResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *PdfToolsResponse) SetFilename(v string) {
	o.Filename = v
}

// GetCreditsRemaining returns the CreditsRemaining field value
func (o *PdfToolsResponse) GetCreditsRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsRemaining
}

// GetCreditsRemainingOk returns a tuple with the CreditsRemaining field value
// and a boolean to check if the value has been set.
func (o *PdfToolsResponse) GetCreditsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsRemaining, true
}

// SetCreditsRemaining sets field value
func (o *PdfToolsResponse) SetCreditsRemaining(v int32) {
	o.CreditsRemaining = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *PdfToolsResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *PdfToolsResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *PdfToolsResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

func (o PdfToolsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PdfToolsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["filename"] = o.Filename
	toSerialize["credits_remaining"] = o.CreditsRemaining
	toSerialize["expires_in"] = o.ExpiresIn
	return toSerialize, nil
}

func (o *PdfToolsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"filename",
		"credits_remaining",
		"expires_in",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPdfToolsResponse := _PdfToolsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPdfToolsResponse)

	if err != nil {
		return err
	}

	*o = PdfToolsResponse(varPdfToolsResponse)

	return err
}

type NullablePdfToolsResponse struct {
	value *PdfToolsResponse
	isSet bool
}

func (v NullablePdfToolsResponse) Get() *PdfToolsResponse {
	return v.value
}

func (v *NullablePdfToolsResponse) Set(val *PdfToolsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePdfToolsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePdfToolsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdfToolsResponse(val *PdfToolsResponse) *NullablePdfToolsResponse {
	return &NullablePdfToolsResponse{value: val, isSet: true}
}

func (v NullablePdfToolsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdfToolsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


