/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentJobStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentJobStatusResponse{}

// AgentJobStatusResponse struct for AgentJobStatusResponse
type AgentJobStatusResponse struct {
	Id string `json:"id"`
	Kind string `json:"kind"`
	Status AppRoutersV1AgentJobStatus `json:"status"`
	TemplateId NullableString `json:"template_id,omitempty"`
	PreviewUrl NullableString `json:"preview_url,omitempty"`
	PreviewExpiresAt NullableString `json:"preview_expires_at,omitempty"`
	Notes NullableString `json:"notes,omitempty"`
	CreditsCharged int32 `json:"credits_charged"`
	ErrorMessage NullableString `json:"error_message,omitempty"`
	ErrorCode NullableString `json:"error_code,omitempty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	CompletedAt NullableString `json:"completed_at,omitempty"`
}

type _AgentJobStatusResponse AgentJobStatusResponse

// NewAgentJobStatusResponse instantiates a new AgentJobStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentJobStatusResponse(id string, kind string, status AppRoutersV1AgentJobStatus, creditsCharged int32, createdAt string, updatedAt string) *AgentJobStatusResponse {
	this := AgentJobStatusResponse{}
	this.Id = id
	this.Kind = kind
	this.Status = status
	this.CreditsCharged = creditsCharged
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewAgentJobStatusResponseWithDefaults instantiates a new AgentJobStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentJobStatusResponseWithDefaults() *AgentJobStatusResponse {
	this := AgentJobStatusResponse{}
	return &this
}

// GetId returns the Id field value
func (o *AgentJobStatusResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentJobStatusResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentJobStatusResponse) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *AgentJobStatusResponse) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AgentJobStatusResponse) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AgentJobStatusResponse) SetKind(v string) {
	o.Kind = v
}

// GetStatus returns the Status field value
func (o *AgentJobStatusResponse) GetStatus() AppRoutersV1AgentJobStatus {
	if o == nil {
		var ret AppRoutersV1AgentJobStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgentJobStatusResponse) GetStatusOk() (*AppRoutersV1AgentJobStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgentJobStatusResponse) SetStatus(v AppRoutersV1AgentJobStatus) {
	o.Status = v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobStatusResponse) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId.Get()) {
		var ret string
		return ret
	}
	return *o.TemplateId.Get()
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobStatusResponse) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateId.Get(), o.TemplateId.IsSet()
}

// HasTemplateId returns a boolean if a field has been set.
func (o *AgentJobStatusResponse) HasTemplateId() bool {
	if o != nil && o.TemplateId.IsSet() {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given NullableString and assigns it to the TemplateId field.
func (o *AgentJobStatusResponse) SetTemplateId(v string) {
	o.TemplateId.Set(&v)
}
// SetTemplateIdNil sets the value for TemplateId to be an explicit nil
func (o *AgentJobStatusResponse) SetTemplateIdNil() {
	o.TemplateId.Set(nil)
}

// UnsetTemplateId ensures that no value is present for TemplateId, not even an explicit nil
func (o *AgentJobStatusResponse) UnsetTemplateId() {
	o.TemplateId.Unset()
}

// GetPreviewUrl returns the PreviewUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobStatusResponse) GetPreviewUrl() string {
	if o == nil || IsNil(o.PreviewUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PreviewUrl.Get()
}

// GetPreviewUrlOk returns a tuple with the PreviewUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobStatusResponse) GetPreviewUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviewUrl.Get(), o.PreviewUrl.IsSet()
}

// HasPreviewUrl returns a boolean if a field has been set.
func (o *AgentJobStatusResponse) HasPreviewUrl() bool {
	if o != nil && o.PreviewUrl.IsSet() {
		return true
	}

	return false
}

// SetPreviewUrl gets a reference to the given NullableString and assigns it to the PreviewUrl field.
func (o *AgentJobStatusResponse) SetPreviewUrl(v string) {
	o.PreviewUrl.Set(&v)
}
// SetPreviewUrlNil sets the value for PreviewUrl to be an explicit nil
func (o *AgentJobStatusResponse) SetPreviewUrlNil() {
	o.PreviewUrl.Set(nil)
}

// UnsetPreviewUrl ensures that no value is present for PreviewUrl, not even an explicit nil
func (o *AgentJobStatusResponse) UnsetPreviewUrl() {
	o.PreviewUrl.Unset()
}

// GetPreviewExpiresAt returns the PreviewExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobStatusResponse) GetPreviewExpiresAt() string {
	if o == nil || IsNil(o.PreviewExpiresAt.Get()) {
		var ret string
		return ret
	}
	return *o.PreviewExpiresAt.Get()
}

// GetPreviewExpiresAtOk returns a tuple with the PreviewExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobStatusResponse) GetPreviewExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviewExpiresAt.Get(), o.PreviewExpiresAt.IsSet()
}

// HasPreviewExpiresAt returns a boolean if a field has been set.
func (o *AgentJobStatusResponse) HasPreviewExpiresAt() bool {
	if o != nil && o.PreviewExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetPreviewExpiresAt gets a reference to the given NullableString and assigns it to the PreviewExpiresAt field.
func (o *AgentJobStatusResponse) SetPreviewExpiresAt(v string) {
	o.PreviewExpiresAt.Set(&v)
}
// SetPreviewExpiresAtNil sets the value for PreviewExpiresAt to be an explicit nil
func (o *AgentJobStatusResponse) SetPreviewExpiresAtNil() {
	o.PreviewExpiresAt.Set(nil)
}

// UnsetPreviewExpiresAt ensures that no value is present for PreviewExpiresAt, not even an explicit nil
func (o *AgentJobStatusResponse) UnsetPreviewExpiresAt() {
	o.PreviewExpiresAt.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobStatusResponse) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobStatusResponse) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *AgentJobStatusResponse) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *AgentJobStatusResponse) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *AgentJobStatusResponse) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *AgentJobStatusResponse) UnsetNotes() {
	o.Notes.Unset()
}

// GetCreditsCharged returns the CreditsCharged field value
func (o *AgentJobStatusResponse) GetCreditsCharged() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsCharged
}

// GetCreditsChargedOk returns a tuple with the CreditsCharged field value
// and a boolean to check if the value has been set.
func (o *AgentJobStatusResponse) GetCreditsChargedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsCharged, true
}

// SetCreditsCharged sets field value
func (o *AgentJobStatusResponse) SetCreditsCharged(v int32) {
	o.CreditsCharged = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobStatusResponse) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobStatusResponse) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *AgentJobStatusResponse) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *AgentJobStatusResponse) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *AgentJobStatusResponse) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *AgentJobStatusResponse) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobStatusResponse) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobStatusResponse) GetErrorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *AgentJobStatusResponse) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableString and assigns it to the ErrorCode field.
func (o *AgentJobStatusResponse) SetErrorCode(v string) {
	o.ErrorCode.Set(&v)
}
// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *AgentJobStatusResponse) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *AgentJobStatusResponse) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *AgentJobStatusResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AgentJobStatusResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AgentJobStatusResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AgentJobStatusResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AgentJobStatusResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AgentJobStatusResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobStatusResponse) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobStatusResponse) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *AgentJobStatusResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableString and assigns it to the CompletedAt field.
func (o *AgentJobStatusResponse) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *AgentJobStatusResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *AgentJobStatusResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

func (o AgentJobStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentJobStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	toSerialize["status"] = o.Status
	if o.TemplateId.IsSet() {
		toSerialize["template_id"] = o.TemplateId.Get()
	}
	if o.PreviewUrl.IsSet() {
		toSerialize["preview_url"] = o.PreviewUrl.Get()
	}
	if o.PreviewExpiresAt.IsSet() {
		toSerialize["preview_expires_at"] = o.PreviewExpiresAt.Get()
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	toSerialize["credits_charged"] = o.CreditsCharged
	if o.ErrorMessage.IsSet() {
		toSerialize["error_message"] = o.ErrorMessage.Get()
	}
	if o.ErrorCode.IsSet() {
		toSerialize["error_code"] = o.ErrorCode.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	return toSerialize, nil
}

func (o *AgentJobStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"kind",
		"status",
		"credits_charged",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentJobStatusResponse := _AgentJobStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentJobStatusResponse)

	if err != nil {
		return err
	}

	*o = AgentJobStatusResponse(varAgentJobStatusResponse)

	return err
}

type NullableAgentJobStatusResponse struct {
	value *AgentJobStatusResponse
	isSet bool
}

func (v NullableAgentJobStatusResponse) Get() *AgentJobStatusResponse {
	return v.value
}

func (v *NullableAgentJobStatusResponse) Set(val *AgentJobStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentJobStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentJobStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentJobStatusResponse(val *AgentJobStatusResponse) *NullableAgentJobStatusResponse {
	return &NullableAgentJobStatusResponse{value: val, isSet: true}
}

func (v NullableAgentJobStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentJobStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


