/*
TemplateFox API

Generate PDFs from HTML templates via API. Design once, generate thousands.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplatesListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplatesListResponse{}

// TemplatesListResponse Response for template list endpoint
type TemplatesListResponse struct {
	Templates []TemplateListItem `json:"templates"`
}

type _TemplatesListResponse TemplatesListResponse

// NewTemplatesListResponse instantiates a new TemplatesListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplatesListResponse(templates []TemplateListItem) *TemplatesListResponse {
	this := TemplatesListResponse{}
	this.Templates = templates
	return &this
}

// NewTemplatesListResponseWithDefaults instantiates a new TemplatesListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplatesListResponseWithDefaults() *TemplatesListResponse {
	this := TemplatesListResponse{}
	return &this
}

// GetTemplates returns the Templates field value
func (o *TemplatesListResponse) GetTemplates() []TemplateListItem {
	if o == nil {
		var ret []TemplateListItem
		return ret
	}

	return o.Templates
}

// GetTemplatesOk returns a tuple with the Templates field value
// and a boolean to check if the value has been set.
func (o *TemplatesListResponse) GetTemplatesOk() ([]TemplateListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Templates, true
}

// SetTemplates sets field value
func (o *TemplatesListResponse) SetTemplates(v []TemplateListItem) {
	o.Templates = v
}

func (o TemplatesListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplatesListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["templates"] = o.Templates
	return toSerialize, nil
}

func (o *TemplatesListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"templates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplatesListResponse := _TemplatesListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplatesListResponse)

	if err != nil {
		return err
	}

	*o = TemplatesListResponse(varTemplatesListResponse)

	return err
}

type NullableTemplatesListResponse struct {
	value *TemplatesListResponse
	isSet bool
}

func (v NullableTemplatesListResponse) Get() *TemplatesListResponse {
	return v.value
}

func (v *NullableTemplatesListResponse) Set(val *TemplatesListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplatesListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplatesListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplatesListResponse(val *TemplatesListResponse) *NullableTemplatesListResponse {
	return &NullableTemplatesListResponse{value: val, isSet: true}
}

func (v NullableTemplatesListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplatesListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


