/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VersionItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionItem{}

// VersionItem Version item in list response
type VersionItem struct {
	// Version number
	VersionNumber int32 `json:"version_number"`
	Tag NullableString `json:"tag,omitempty"`
	Description NullableString `json:"description,omitempty"`
	// ISO 8601 timestamp
	CreatedAt string `json:"created_at"`
}

type _VersionItem VersionItem

// NewVersionItem instantiates a new VersionItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionItem(versionNumber int32, createdAt string) *VersionItem {
	this := VersionItem{}
	this.VersionNumber = versionNumber
	this.CreatedAt = createdAt
	return &this
}

// NewVersionItemWithDefaults instantiates a new VersionItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionItemWithDefaults() *VersionItem {
	this := VersionItem{}
	return &this
}

// GetVersionNumber returns the VersionNumber field value
func (o *VersionItem) GetVersionNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VersionNumber
}

// GetVersionNumberOk returns a tuple with the VersionNumber field value
// and a boolean to check if the value has been set.
func (o *VersionItem) GetVersionNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionNumber, true
}

// SetVersionNumber sets field value
func (o *VersionItem) SetVersionNumber(v int32) {
	o.VersionNumber = v
}

// GetTag returns the Tag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VersionItem) GetTag() string {
	if o == nil || IsNil(o.Tag.Get()) {
		var ret string
		return ret
	}
	return *o.Tag.Get()
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VersionItem) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tag.Get(), o.Tag.IsSet()
}

// HasTag returns a boolean if a field has been set.
func (o *VersionItem) HasTag() bool {
	if o != nil && o.Tag.IsSet() {
		return true
	}

	return false
}

// SetTag gets a reference to the given NullableString and assigns it to the Tag field.
func (o *VersionItem) SetTag(v string) {
	o.Tag.Set(&v)
}
// SetTagNil sets the value for Tag to be an explicit nil
func (o *VersionItem) SetTagNil() {
	o.Tag.Set(nil)
}

// UnsetTag ensures that no value is present for Tag, not even an explicit nil
func (o *VersionItem) UnsetTag() {
	o.Tag.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VersionItem) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VersionItem) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *VersionItem) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *VersionItem) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *VersionItem) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *VersionItem) UnsetDescription() {
	o.Description.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *VersionItem) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *VersionItem) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *VersionItem) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o VersionItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version_number"] = o.VersionNumber
	if o.Tag.IsSet() {
		toSerialize["tag"] = o.Tag.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *VersionItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version_number",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVersionItem := _VersionItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVersionItem)

	if err != nil {
		return err
	}

	*o = VersionItem(varVersionItem)

	return err
}

type NullableVersionItem struct {
	value *VersionItem
	isSet bool
}

func (v NullableVersionItem) Get() *VersionItem {
	return v.value
}

func (v *NullableVersionItem) Set(val *VersionItem) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionItem) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionItem(val *VersionItem) *NullableVersionItem {
	return &NullableVersionItem{value: val, isSet: true}
}

func (v NullableVersionItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


