/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.13.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentJobCreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentJobCreatedResponse{}

// AgentJobCreatedResponse struct for AgentJobCreatedResponse
type AgentJobCreatedResponse struct {
	JobId string `json:"job_id"`
	Status string `json:"status"`
	CreditsCharged int32 `json:"credits_charged"`
	CreditsRemaining int32 `json:"credits_remaining"`
}

type _AgentJobCreatedResponse AgentJobCreatedResponse

// NewAgentJobCreatedResponse instantiates a new AgentJobCreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentJobCreatedResponse(jobId string, status string, creditsCharged int32, creditsRemaining int32) *AgentJobCreatedResponse {
	this := AgentJobCreatedResponse{}
	this.JobId = jobId
	this.Status = status
	this.CreditsCharged = creditsCharged
	this.CreditsRemaining = creditsRemaining
	return &this
}

// NewAgentJobCreatedResponseWithDefaults instantiates a new AgentJobCreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentJobCreatedResponseWithDefaults() *AgentJobCreatedResponse {
	this := AgentJobCreatedResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *AgentJobCreatedResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *AgentJobCreatedResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *AgentJobCreatedResponse) SetJobId(v string) {
	o.JobId = v
}

// GetStatus returns the Status field value
func (o *AgentJobCreatedResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AgentJobCreatedResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AgentJobCreatedResponse) SetStatus(v string) {
	o.Status = v
}

// GetCreditsCharged returns the CreditsCharged field value
func (o *AgentJobCreatedResponse) GetCreditsCharged() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsCharged
}

// GetCreditsChargedOk returns a tuple with the CreditsCharged field value
// and a boolean to check if the value has been set.
func (o *AgentJobCreatedResponse) GetCreditsChargedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsCharged, true
}

// SetCreditsCharged sets field value
func (o *AgentJobCreatedResponse) SetCreditsCharged(v int32) {
	o.CreditsCharged = v
}

// GetCreditsRemaining returns the CreditsRemaining field value
func (o *AgentJobCreatedResponse) GetCreditsRemaining() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsRemaining
}

// GetCreditsRemainingOk returns a tuple with the CreditsRemaining field value
// and a boolean to check if the value has been set.
func (o *AgentJobCreatedResponse) GetCreditsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsRemaining, true
}

// SetCreditsRemaining sets field value
func (o *AgentJobCreatedResponse) SetCreditsRemaining(v int32) {
	o.CreditsRemaining = v
}

func (o AgentJobCreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentJobCreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	toSerialize["status"] = o.Status
	toSerialize["credits_charged"] = o.CreditsCharged
	toSerialize["credits_remaining"] = o.CreditsRemaining
	return toSerialize, nil
}

func (o *AgentJobCreatedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
		"status",
		"credits_charged",
		"credits_remaining",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentJobCreatedResponse := _AgentJobCreatedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentJobCreatedResponse)

	if err != nil {
		return err
	}

	*o = AgentJobCreatedResponse(varAgentJobCreatedResponse)

	return err
}

type NullableAgentJobCreatedResponse struct {
	value *AgentJobCreatedResponse
	isSet bool
}

func (v NullableAgentJobCreatedResponse) Get() *AgentJobCreatedResponse {
	return v.value
}

func (v *NullableAgentJobCreatedResponse) Set(val *AgentJobCreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentJobCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentJobCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentJobCreatedResponse(val *AgentJobCreatedResponse) *NullableAgentJobCreatedResponse {
	return &NullableAgentJobCreatedResponse{value: val, isSet: true}
}

func (v NullableAgentJobCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentJobCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


