/*
TemplateFox API

Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package templatefox

import (
	"encoding/json"
	"fmt"
)

// AppRoutersV1PdfAsyncExportType PDF export type options for async generation
type AppRoutersV1PdfAsyncExportType string

// List of app__routers__v1__pdf_async__ExportType
const (
	URL AppRoutersV1PdfAsyncExportType = "url"
)

// All allowed values of AppRoutersV1PdfAsyncExportType enum
var AllowedAppRoutersV1PdfAsyncExportTypeEnumValues = []AppRoutersV1PdfAsyncExportType{
	"url",
}

func (v *AppRoutersV1PdfAsyncExportType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppRoutersV1PdfAsyncExportType(value)
	for _, existing := range AllowedAppRoutersV1PdfAsyncExportTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppRoutersV1PdfAsyncExportType", value)
}

// NewAppRoutersV1PdfAsyncExportTypeFromValue returns a pointer to a valid AppRoutersV1PdfAsyncExportType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppRoutersV1PdfAsyncExportTypeFromValue(v string) (*AppRoutersV1PdfAsyncExportType, error) {
	ev := AppRoutersV1PdfAsyncExportType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppRoutersV1PdfAsyncExportType: valid values are %v", v, AllowedAppRoutersV1PdfAsyncExportTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppRoutersV1PdfAsyncExportType) IsValid() bool {
	for _, existing := range AllowedAppRoutersV1PdfAsyncExportTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to app__routers__v1__pdf_async__ExportType value
func (v AppRoutersV1PdfAsyncExportType) Ptr() *AppRoutersV1PdfAsyncExportType {
	return &v
}

type NullableAppRoutersV1PdfAsyncExportType struct {
	value *AppRoutersV1PdfAsyncExportType
	isSet bool
}

func (v NullableAppRoutersV1PdfAsyncExportType) Get() *AppRoutersV1PdfAsyncExportType {
	return v.value
}

func (v *NullableAppRoutersV1PdfAsyncExportType) Set(val *AppRoutersV1PdfAsyncExportType) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRoutersV1PdfAsyncExportType) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRoutersV1PdfAsyncExportType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRoutersV1PdfAsyncExportType(val *AppRoutersV1PdfAsyncExportType) *NullableAppRoutersV1PdfAsyncExportType {
	return &NullableAppRoutersV1PdfAsyncExportType{value: val, isSet: true}
}

func (v NullableAppRoutersV1PdfAsyncExportType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRoutersV1PdfAsyncExportType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

